// Batch 11–13 (MASTER-arket, flik "www", 2026-09-13 – 09-16) — LÅSTA FAKTA.
// Axel 2026-09-23: "Dessa ska upp på bäverbutiken. Både svenska och norska. Bara att börja kötta!"
// Offert: https://docs.google.com/spreadsheets/d/1zxPXYeyx228RVQ16-vrN19m-K2jKdq4x5snQ2KXAaj8
//
// Källor per produkt: Axels radnamn + leverantörsref i arket, CWD:s QC-bilder 2026-09-18
// (temu/qc/2026-09-18-cwd-qc.md) och CWD:s svar 2026-09-19. AliExpress-sidorna går inte att
// läsa från molnet — inget utöver det här får påstås. Räkneord är låsta mot arket.
//
// status: 'bygg' = skapas nu med QC-bilden som hero · 'vanta' = skapas när Axels skörd
// (BILDSKORD-BATCH11.md) eller CWD:s svar kommit. orsak står i `vanta`.
// landat = USD qty 1 ur arket (SE resp. NO). Priser räknas i priser.mjs.

const B = '/tmp/claude-0/-home-user-yognftnfgn/4034ad3c-cd7c-513c-944c-3efffa125d52/scratchpad/qc/ut/QC-bilder';
const K = (s) => `gid://shopify/TaxonomyCategory/${s}`;

export const FAKTA = {
  // ── Batch 11 ──────────────────────────────────────────────────────────────
  bathuv: { batch: 11, sku: 'TEMU-B11-BATHUV', kategori: K('vp-1-5-3'), radnamn: 'Båthuven 600D för trailerbåt 17–19 fot',
    landat: { se: 31.09, no: 36.35 }, latt: { tyg: '600D', batlangd: '17–19 fot', matt: '600 × 310 cm' },
    status: 'vanta', vanta: 'ingen bild — väntar på skörden' },
  kamadohuv: { batch: 11, sku: 'TEMU-B11-KAMADOHUV', kategori: K('hg-11-6-19-4'), radnamn: 'Kamadohuven 600D',
    landat: { se: 19.12, no: 22.47 }, latt: { tyg: '600D', matt: '80 × 102 cm', farg: 'svart (grå finns också)', forvaringspase: true },
    qc: [`${B}/qc-20260917235530.png`, `${B}/qc-20260917235601.png`],
    status: 'vanta', vanta: 'QC-bilden visar GRÅ huv, vi säljer svart — väntar på skörden (svart bild)' },
  kajakhuv: { batch: 11, sku: 'TEMU-B11-KAJAKHUV', kategori: K('sg-4-1-1-4'), radnamn: 'Kajakhuven formsydd',
    landat: { se: 18.69, no: 21.17 }, latt: { ref: '230*165-46', farger: ['svart', 'silvergrå'] },
    status: 'vanta', vanta: 'ingen bild, oklart mått (230*165-46) — väntar på skörden' },
  varmesulor: { batch: 11, sku: 'TEMU-B11-VARMESULOR', kategori: K('hb-3-9-4'), radnamn: 'Värmesulorna för älgpasset',
    landat: { se: 27.14, no: 28.51 },
    latt: { par: 1, fjarrkontroll: true, laddning: 'USB-kabel ingår', batteri: '2000 mAh (CWD: "similar, 2000mA")',
      storlekar: 'klipplinjer 41–46 tryckta på sulan ("Do not cut below this line")',
      lagen: 'tre värmelägen enligt trycket på sulan: hög / medel / låg', ingar: ['2 sulor', 'fjärrkontroll med nyckelring', 'USB-laddkabel', 'manual'] },
    obs: 'Drifttid per läge (4/6/10 h) står på sulan som leverantörens uppgift — skrivs bara som "enligt leverantören". Inga watt, inga temperaturer.',
    qc: [`${B}/qc-20260917235613.png`], status: 'bygg' },
  krukvaxthuv: { batch: 11, sku: 'TEMU-B11-KRUKVAXTHUV', kategori: K('hg-12-1'), radnamn: 'Krukväxthuven med dragkedja, 3-pack',
    landat: { se: 17.27, no: 20.04 },
    latt: { antal: 3, matt: '120 × 180 cm', dragkedja: true, dragsko: true, material: 'fiberduk (non-woven)', farg: 'beige',
      forpackning: 'etikett "PLANT COVER – Wind · Rain · Snow · Frost" med storlekslista, 120 × 180 ibockad' },
    qc: [`${B}/qc-20260917235622.png`], flerpack: 3, status: 'bygg' },
  bikupsjacka: { batch: 11, sku: 'TEMU-B11-BIKUPSJACKA', kategori: K('bi-2-1-5-3'), radnamn: 'Bikupans vinterjacka',
    landat: { se: 14.65, no: 16.55 },
    latt: { matt: '194 × 46 cm', utsida: 'svart väv', insida: 'silverfärgad folie (syns på bilden)', fasten: 'spännremmar med spännen' },
    qc: [`${B}/qc-20260917235629.png`], status: 'bygg' },
  maskinhylla: { batch: 11, sku: 'TEMU-B11-MASKINHYLLA', kategori: K('ha-6-24'), radnamn: 'Maskinhyllan för 4 elverktyg',
    landat: { se: 32.94, no: 40.66 }, latt: { matt: '42 × 20 × 35 cm', platser: 4 },
    status: 'vanta', vanta: 'ingen bild — väntar på skörden' },
  ljusslingevindor: { batch: 11, sku: 'TEMU-B11-LJUSSLINGEVINDOR', kategori: K('hg-3-58'), radnamn: 'Ljusslingevindorna 10-pack',
    landat: { se: 10.96, no: 12.85 },
    latt: { antal: 10, material: 'svart plast', form: 'vinda med halvmåneformade ändar och handtagshål (syns på bilden)' },
    obs: 'Inga mått i arket — inga cm. CWD: "similar".',
    qc: [`${B}/qc-20260918000609.png`], flerpack: 10, status: 'bygg' },
  makitahallare: { batch: 11, sku: 'TEMU-B11-MAKITAHALLARE', kategori: K('ha-6-24'), radnamn: 'Makita-hållaren 5-pack (maskinen på väggen)',
    landat: { se: 9.22, no: 11.31 },
    latt: { antal: 5, farg: 'turkos', montering: 'skruvas i väggen — fyra hål i plattan', passar: 'maskiner/batterier med Makita 18V-fäste (Axels radnamn)' },
    obs: 'Ingen lastvikt i arket. Skruvar: syns inte på bilden — påstå inte att de ingår.',
    qc: [`${B}/qc-20260918001456.png`], flerpack: 5, status: 'bygg' },

  // ── Batch 12 ──────────────────────────────────────────────────────────────
  fonstertermomatta: { batch: 12, sku: 'TEMU-B12-FONSTERTERMOMATTA', kategori: K('vp-1-5-3'), radnamn: 'Fönstertermomattan för husvagn, 2-pack',
    landat: { se: 15.58, no: 17.76 }, latt: { antal: 2, matt: '70 × 80 cm' }, flerpack: 2,
    status: 'vanta', vanta: 'ingen bild — väntar på skörden' },
  varmemuff: { batch: 12, sku: 'TEMU-B12-VARMEMUFF', kategori: K('sg-4-9-3'), radnamn: 'Värmemuffen för fisket och passet',
    landat: { se: 19.87, no: 21.24 }, latt: {}, status: 'vanta', vanta: 'slut hos leverantören, tillbaka tidigast om en månad — pre-order när CWD ger ett datum',
    obs: 'Arkets rad 62 ("OBS DENNA PRODUKTEN ÄR OUT OF STOCK … PRE ORDER") är den här produktens qty-2-rad: 19,69 = 2 × 9,85 USD, frakt 15,82. Noten gäller alltså Värmemuffen (verifierat 2026-09-23).' },
  laktarponcho: { batch: 12, sku: 'TEMU-B12-LAKTARPONCHO', kategori: K('aa-1-10-2-8'), radnamn: 'Läktarponchon med värme',
    landat: { se: 26.32, no: 24.07 }, latt: {}, status: 'vanta', vanta: 'ingen bild, inga fakta — väntar på skörden' },
  rcdrift: { batch: 12, sku: 'TEMU-B12-RCDRIFT', kategori: K('tg-5-18-3'), radnamn: 'Radiostyrd drifting bil 1:24',
    landat: { se: 20.75, no: 24.07 },
    latt: { skala: '1:24', drivning: '4WD (kartongen)', toppfart: '20 km/h (Temu-titeln)', ljus: 'LED', farg: 'grå (QC-bilden)',
      ingar: ['bil', 'pistolgreppskontroll', '4 extra driftdäck', '5 koner', '2 tunnor', 'skruvmejsel', 'USB-laddkabel', 'manual'] },
    obs: 'Räkna på QC-bilden: 4 extra däck, 5 koner, 2 tunnor. Inget om batteritid eller räckvidd.',
    qc: [`${B}/qc-20260918011009.png`], status: 'bygg' },
  rcoffroad: { batch: 12, sku: 'TEMU-601099746858349', kategori: K('tg-5-18-3'), radnamn: 'Offroad radiostyrd bil 1:16',
    landat: { se: 31.68, no: 39.11 },
    latt: { skala: '1:16', toppfart: '20 km/h', kaross: 'metallegering', batterier: '2 st (variant "Dubbel Batteri")', speltid: 'upp till 50 min med två batterier (leverantören)', radio: '2,4 GHz', drivning: '2WD (kartongen)', spanning: '3,7 V' },
    obs: 'FINNS REDAN I SE sedan 2026-07-22 (gid://shopify/Product/16349632299357, 799 kr, gammal sidmall med "14 dagars ångerrätt"). Åtgärd: skriv om SE-sidan enligt playbooken, sätt ny cogs, klona till NO med SE:s fem bilder.',
    seFinns: 'gid://shopify/Product/16349632299357', status: 'bygg',
    farger: ['Blå', 'Svart', 'Orange'] /* Axel 2026-09-23. Varianter: rc-farger.mjs. Bilderna för alla tre färger ligger redan i SE (kontaktark rc-se.jpg): 1 blå, 3 svart, 5 orange */ },

  // ── Batch 13 ──────────────────────────────────────────────────────────────
  vedklyvshuv: { batch: 13, sku: 'TEMU-B13-VEDKLYVSHUV', kategori: K('hg-12-4-16'), radnamn: 'Vedklyvshuven 210D',
    landat: { se: 12.5, no: 14.1 }, latt: { tyg: '210D', farg: 'svart', dragsko: true, leverans: 'make to order, 7 dagar hos fabriken' },
    obs: 'Inga mått i arket — inga cm. Bilden visar huven över en vedklyv på ben.',
    qc: [`${B}/qc-20260918011726.png`], status: 'bygg' },
  scooterkapell: { batch: 13, sku: 'TEMU-B13-SCOOTERKAPELL', kategori: K('hb-1-17-2-1'), radnamn: 'Promenadscooterns regnkapell',
    landat: { se: 16.35, no: 18.24 }, latt: { matt: '190 × 71 × 117 cm', farg: 'svart' },
    qc: [`${B}/qc-20260918012658.png`], status: 'vanta', vanta: 'QC-bilden visar bara den hoppackade påsen — väntar på skörden' },
  poolpumphuv: { batch: 13, sku: 'TEMU-B13-POOLPUMPHUV', kategori: K('hg-18-1'), radnamn: 'Poolvärmepumpens vinterhuv',
    landat: { se: 15.44, no: 16.66 },
    latt: { matt: '101 × 86 × 78 cm', tyg: '210D', farg: 'svart', ventilation: 'ventilationsöppning på sidan', fasten: 'öljetter med snöre i nederkant' },
    qc: [`${B}/qc-20260918012844.png`], status: 'bygg' },
  tradansikte: { batch: 13, sku: 'TEMU-B13-TRADANSIKTE', kategori: K('hg-3'), radnamn: 'Trädansiktet — gubben i trädet',
    landat: { se: 10.19, no: 11.21 }, latt: {}, status: 'vanta', vanta: 'ingen bild — väntar på skörden' },
  regnkedja: { batch: 13, sku: 'TEMU-B13-REGNKEDJA', kategori: K('hg-3-54'), radnamn: 'Regnkedjan 3,8 m med 12 koppar',
    landat: { se: 21.69, no: 25.48 },
    latt: { langd: '3,8 m', koppar: 12, material: 'metall i kopparfärg (bilden)', form: 'koppar med rutmönster på kedja' },
    obs: '12 koppar räknade på QC-bilden. Ingen uppgift om diameter eller montering.',
    qc: [`${B}/qc-20260918013621.png`], status: 'bygg' },
  snosmaltmatta: { batch: 13, sku: 'TEMU-B13-SNOSMALTMATTA', kategori: K('hg-12-5'), radnamn: 'Snösmältmattan för trappan',
    landat: { se: 28.34, no: 31.98 }, latt: { matt: '25,4 × 76,2 cm', oljetter: 4, sladdar: 'två sladdar med kopplingar (seriekoppling)' },
    qc: [`${B}/qc-20260918013629.png`], status: 'vanta', vanta: 'spänning/EU-kontakt inte bekräftad av CWD — el-produkt, säljs inte förrän det är svart på vitt' },
  rullknivslip: { batch: 13, sku: 'TEMU-B13-RULLKNIVSLIP', kategori: K('hg-11-7-30-3'), radnamn: 'Rullknivslipen i trä, 2 diamantskivor',
    landat: { se: 16.85, no: 18.38 },
    latt: { delar: 'magnetiskt vinkelblock i trä märkt 20° + rulle i trä med slipskivor', skivor: '2 diamantskivor (arket)', forpackning: 'svart kartong "Rolling Sharpener", manual' },
    obs: 'Blocket är märkt 20° på QC-bilden. Om det finns fler vinklar (15°) står det inte i arket — påstå inte.',
    qc: [`${B}/qc-20260918013657.png`], status: 'bygg' },
  highlandcow: { batch: 13, sku: 'TEMU-B13-HIGHLANDCOW', kategori: K('hg-3-58-1'), radnamn: 'Highland Cow-kalendern 3D, 24 figurer',
    landat: { se: 12.85, no: 13.86 },
    latt: { antal: 24, figurer: 'små highland cow-figurer i plast, i blister', ask: 'tryckt "Highland Cow Advent Calendar 2026", "24 happy Highland cows"' },
    obs: 'QC-bilden har leverantörens vattenstämpel över nedre vänstra asken — beskär till övre halvan (två askar). Figurerna kan inte räknas till 24 på bilden.',
    qc: [`${B}/qc-20260918013722.png`], status: 'bygg' },
  adelstenskalender: { batch: 13, sku: 'TEMU-B13-ADELSTENSKALENDER', kategori: K('hg-3-58-1'), radnamn: 'Ädelstenskalendern, 24 grävblock',
    landat: { se: 13.02, no: 13.98 }, latt: { antal: 24, luckor: 24, ask: 'röd "Merry Christmas"-ask med tomte, numrerade luckor 1–24 (QC-bilden)' },
    obs: 'Axel 2026-09-23: den röda asken ÄR ädelstenskalendern. QC-bilden har skärmkanter (ikoner uppe till höger, klocka nere till vänster) — beskuren till asken. Stentyp, blockstorlek, verktyg och ålder är okända och påstås inte.',
    qc: [`${B}/qc-20260918013733.png`], status: 'bygg' },
  cykelhallarskydd: { batch: 13, sku: 'TEMU-B13-CYKELHALLARSKYDD', kategori: K('vp-1-5-3'), radnamn: 'Husbilens cykelhållarskydd 2 cyklar',
    landat: { se: 20.08, no: 22.85 }, latt: { cyklar: 2, farg: 'svart (QC-bilden)' },
    obs: 'Arkets ref-kolumn är TOM: inga mått, inget material, ingen fästning — påstås inte. QC-bild 25 visar det svarta kapellet över cyklar på en hållare inomhus. Jag dömde bilden fel som ATV-kapell 2026-09-18; Axel rättade 2026-09-23 ("det är bike rack cover"). Frågan till CWD om ny offert är struken.',
    qc: [`${B}/qc-20260918013741.png`], status: 'bygg' },
  takachuv: { batch: 13, sku: 'TEMU-B13-TAKACHUV', kategori: K('hg-8-1-1'), radnamn: 'Husbilens tak-AC-huv',
    landat: { se: 12.12, no: 12.98 }, latt: { matt: '80 × 80 × 38 cm', farg: 'svart', dragsko: true },
    qc: [`${B}/qc-20260918013753.png`], status: 'bygg' },
  krukbarrem: { batch: 13, sku: 'TEMU-B13-KRUKBARREM', kategori: K('hg-12-1-5'), radnamn: 'Krukbärremmen — olivträdet in, 90 kg',
    landat: { se: 15.35, no: 15.35 }, latt: { last: '90 kg' }, status: 'vanta', vanta: 'ingen bild — väntar på skörden' },
  buskjacka: { batch: 13, sku: 'TEMU-B13-BUSKJACKA', kategori: K('hg-12-1'), radnamn: 'Buskjackan med dragkedja, 2-pack',
    landat: { se: 11.65, no: 13.4 },
    latt: { antal: 2, matt: '120 × 180 cm (CWD 2026-09-19)', dragkedja: true, dragsko: 'i nederkant', material: 'fiberduk i polypropen (förpackningen)', farg: 'beige' },
    obs: 'Förpackningen lovar "water resistance" — skrivs inte. Bild 28 visar huven på en kruka med dragskon åtdragen.',
    qc: [`${B}/qc-20260918013808.png`, `${B}/qc-20260918013816.png`], flerpack: 2, status: 'bygg' },
  sorkkorgar: { batch: 13, sku: 'TEMU-B13-SORKKORGAR', kategori: K('hg-12-1'), radnamn: 'Sorkkorgarna i rostfritt, 15-pack',
    landat: { se: 16.35, no: 18.53 }, latt: { antal: 15, material: 'rostfritt', ref: '50*55 cm (?)' }, flerpack: 15,
    status: 'vanta', vanta: 'ingen bild, måttet oklart — väntar på skörden' },
  husbilskalender: { batch: 13, sku: 'TEMU-B13-HUSBILSKALENDER', kategori: K('hg-3-58-1'), radnamn: 'Husbilskalendern, 24 retrobussar',
    landat: { se: 9.72, no: 11.81 }, latt: { antal: 24 },
    qc: [`${B}/qc-20260918013840.png`, `${B}/qc-20260918013848.png`],
    status: 'vanta', vanta: 'asken är tryckt "VOLKSWAGEN CAMPER" — varumärkesrisk, Axel avgör' },
  slangboxhuv: { batch: 13, sku: 'TEMU-B13-SLANGBOXHUV', kategori: K('ha-6-24-1'), radnamn: 'Slangboxhuven isolerad 55 cm',
    landat: { se: 10.13, no: 11.88 }, latt: { matt: '55 × 55 × 30 cm' }, status: 'vanta', vanta: 'ingen bild — väntar på skörden' },
  lovsilar: { batch: 13, sku: 'TEMU-B13-LOVSILAR', kategori: K('ha-2-13-1'), radnamn: 'Lövsilarna för stuprören, 6-pack',
    landat: { se: 9.64, no: 10.89 },
    latt: { antal: 6, material: 'rostfritt nät', form: 'formas till en strut som sätts i stuprörets mynning (bild 32)' },
    obs: 'Ingen diameter i arket — inga cm.',
    qc: [`${B}/qc-20260918013823.png`, `${B}/qc-20260918013855.png`], flerpack: 6, status: 'bygg' },
  regntunnehuv: { batch: 13, sku: 'TEMU-B13-REGNTUNNEHUV', kategori: K('hg-12-1-17'), radnamn: 'Regntunnehuven 200 L med dragsko',
    landat: { se: 8.59, no: 10.19 }, latt: { volym: '200 L', dragsko: true }, status: 'vanta', vanta: 'ingen bild — väntar på skörden' },
  elcykeljacka: { batch: 13, sku: 'TEMU-B13-ELCYKELJACKA', kategori: K('sg-4-4-1'), radnamn: 'Elcykelbatteriets vinterjacka, 2-pack',
    landat: { se: 8.85, no: 10.55 },
    latt: { antal: 2, material: 'stickad, olivgrön (bilden)', fasten: 'tryckknapp' },
    obs: 'Inga mått i arket — inga cm, ingen batterimodell.',
    qc: [`${B}/qc-20260918005802.png`], flerpack: 2, status: 'bygg' },
  bordsfotboll: { batch: 13, sku: 'TEMU-B13-BORDSFOTBOLL', kategori: K('sg-3'), radnamn: 'Competetive football',
    landat: { se: 11.73, no: 13.62 },
    latt: { spelare: 2, bollar: 6, alder: '3+', kartong: '"Tabletop Games Football", engelsk text', regel: 'först till 10 poäng vinner (kartongens instruktion)', tillbehor: 'fotbollsplan med sarg, skjuthandtag, målburar, flaggstolpar, poängräknare' },
    obs: '6 bollar enligt CWD 2026-09-19. Kartongen säger 3+.',
    qc: [`${B}/O1CN01TZu0UC1aEzmH3TiJt_!!2220028103299-0-cib.jpg`, `${B}/O1CN016qqrva1aEzmH3TVrE_!!2220028103299-0-cib.jpg`] /* framsida först, baksida (instruktioner) som detalj */, status: 'bygg' },
  magnetblock: { batch: 13, sku: 'TEMU-B13-MAGNETBLOCK', kategori: K('tg-5-7'), radnamn: 'Magnetiska byggblock',
    landat: { se: 24.50, no: 28.81 },
    latt: { antal: 200, kub: 'magnetiska kuber med blocktryck ("Magnetic Building Cubes – Build your own 3D world")', alder: '3+' },
    obs: '200-PACK är enda varianten nu (CWD: "200pcs only" ersätter 150-raden; 300-pack finns offererat till 29,12 USD men saknar bild — läggs till som variant när skörden ger en 300-bild). Antalet i titel + badge + första bullet.',
    qc: [`${B}/1789743469257.png`, `${B}/1789743471290.png`], flerpack: 200, status: 'bygg' },
};

export const HOPPAS = {
  dammvarmare: 'Dammvärmaren 500 W — CWD 2026-09-19: bara US-version (110 V/US-kontakt). Säljs inte.',
  minikedjesag: 'Minikedjesågen för Makita-batteri — ingen quote ("not in stock").',
  honslucka: 'Automatiska hönsluckan — ingen quote ("out of stock").',
  fagelholk: 'Fågelholken med WiFi-kamera — ingen quote (MOQ 500).',
};
