// Utrullning 2026-08-22: all copy för NO/DK/FI/UK, 8 produkter.
// Skriven enligt butikens playbook (7-block, utfall-först-bullets, inga
// hastighets- eller absolutlöften) med fakta verifierade mot Temu-galleriet.

export const GARANTI = {
  no: '30 dagers åpent kjøp – liker du det ikke, får du pengene tilbake. Smidig levering og trygg betaling med Klarna. 🦫',
  da: '30 dages fuld returret – kan du ikke lide det, får du pengene tilbage. Smidig levering og tryg betaling med Klarna. 🦫',
  fi: '30 päivän palautusoikeus – jos et pidä siitä, saat rahasi takaisin. Sujuva toimitus ja turvallinen maksu Klarnalla. 🦫',
  en: "30-day returns – if you don't love it, you get your money back. Smooth delivery and secure payment with Klarna. 🦫",
};

export const T = {
  pingis: {
    no: {
      titel: 'Bordtennisnett Uttrekkbart – 2 Racketer & 6 Baller',
      problemH: 'Et pingpongbord sluker et helt rom',
      problemP: 'Alle vil spille, men et ekte bord koster tusenvis og krever plass som ikke finnes. Så blir det ikke noe spill.',
      losningH: 'Nettet som gjør spisebordet om til pingpongbord',
      losningP: 'Klem de to stolpene fast på en valgfri bordkant og trekk nettet ut mellom dem – det strekker seg opptil 1,7 meter og dekker hele bordet. To racketer og seks baller følger med, så kampen kan starte med en gang. Når det skal spises middag, trekker du nettet sammen og legger alt tilbake i esken.',
      bullets: [
        '<strong>Hvilket som helst bord blir spillebane</strong> – nettet trekkes ut opptil 1,7 m, ingen verktøy',
        '<strong>Alt følger med</strong> – 2 racketer og 6 baller i settet',
        '<strong>Setter ingen merker</strong> – gummikledde klemmer, passer bordplater opptil 5 cm',
        '<strong>Står stødig også ute</strong> – sklisikker gummibase',
        '<strong>Ryddet bort på sekunder</strong> – nettet er uttrekkbart og hele settet får plass i esken',
      ],
      option: 'Farge', varden: ['Svart', 'Oransje'],
      alt: { main: 'Uttrekkbart bordtennisnett med to racketer og seks baller', svart: 'Settet med svarte nettholdere', orange: 'Settet med oransje nettholdere', info1: 'Nettet trukket ut over hele bordet', info2: 'Nettet trekkes ut til 1,7 m – sklisikker gummibase' },
    },
    da: {
      titel: 'Bordtennisnet Udtrækkeligt – 2 Bat & 6 Bolde',
      problemH: 'Et bordtennisbord sluger et helt rum',
      problemP: 'Alle vil spille, men et rigtigt bord koster tusindvis og kræver plads, der ikke findes. Så bliver der ikke spillet.',
      losningH: 'Nettet der gør spisebordet til bordtennisbord',
      losningP: 'Klem de to holdere fast på en valgfri bordkant og træk nettet ud imellem dem – det strækker sig op til 1,7 meter og dækker hele bordet. To bat og seks bolde følger med, så kampen kan starte med det samme. Når der skal spises aftensmad, trækker du nettet sammen og lægger det hele tilbage i æsken.',
      bullets: [
        '<strong>Ethvert bord bliver til bane</strong> – nettet trækkes ud op til 1,7 m, intet værktøj',
        '<strong>Alt følger med</strong> – 2 bat og 6 bolde i sættet',
        '<strong>Efterlader ingen mærker</strong> – gummibeklædte klemmer, passer bordplader op til 5 cm',
        '<strong>Står fast – også udenfor</strong> – skridsikker gummibund',
        '<strong>Ryddet væk på sekunder</strong> – nettet er udtrækkeligt, og hele sættet er i æsken igen',
      ],
      option: 'Farve', varden: ['Sort', 'Orange'],
      alt: { main: 'Udtrækkeligt bordtennisnet med to bat og seks bolde', svart: 'Sættet med sorte netholdere', orange: 'Sættet med orange netholdere', info1: 'Nettet trukket ud over hele bordet', info2: 'Nettet trækkes ud til 1,7 m – skridsikker gummibund' },
    },
    fi: {
      titel: 'Pöytätennisverkko Sisäänvedettävä – 2 Mailaa & 6 Palloa',
      problemH: 'Pingispöytä nielaisee kokonaisen huoneen',
      problemP: 'Kaikki haluavat pelata, mutta oikea pöytä maksaa satoja ja vaatii tilaa, jota ei ole. Siksi peli jää pelaamatta.',
      losningH: 'Verkko, joka muuttaa ruokapöydän pingispöydäksi',
      losningP: 'Kiinnitä telineet valitsemasi pöydän reunaan ja vedä verkko niiden väliin – se venyy jopa 1,7 metriin ja kattaa koko pöydän. Kaksi mailaa ja kuusi palloa kuuluvat settiin, joten peli voi alkaa heti. Kun on ruoka-aika, verkko vedetään kasaan ja kaikki mahtuu takaisin laatikkoon.',
      bullets: [
        '<strong>Mikä tahansa pöytä muuttuu pelikentäksi</strong> – verkko venyy jopa 1,7 m, ei työkaluja',
        '<strong>Kaikki mukana heti</strong> – 2 mailaa ja 6 palloa',
        '<strong>Ei jälkiä pöytään</strong> – kumipäällysteiset kiinnikkeet, sopii jopa 5 cm pöytälevyille',
        '<strong>Pysyy paikallaan myös ulkona</strong> – luistamaton kumijalusta',
        '<strong>Siivottu sekunneissa</strong> – verkko vetäytyy kasaan ja koko setti mahtuu laatikkoon',
      ],
      option: 'Väri', varden: ['Musta', 'Oranssi'],
      alt: { main: 'Sisäänvedettävä pöytätennisverkko, kaksi mailaa ja kuusi palloa', svart: 'Setti mustilla verkkotelineillä', orange: 'Setti oransseilla verkkotelineillä', info1: 'Verkko vedettynä koko pöydän yli', info2: 'Verkko venyy 1,7 metriin – luistamaton kumijalusta' },
    },
    en: {
      titel: 'Retractable Table Tennis Net – 2 Paddles & 6 Balls',
      problemH: 'A ping pong table swallows an entire room',
      problemP: "Everyone wants to play, but a real table costs a fortune and needs space you haven't got. So the game never happens.",
      losningH: 'The net that turns your dining table into a ping pong table',
      losningP: "Clamp the two posts onto any table edge and stretch the net between them – it extends up to 1.7 metres and covers the whole table. Two paddles and six balls are included, so the match can start right away. When it's time for dinner, the net retracts and everything goes back in the box.",
      bullets: [
        '<strong>Any table becomes a court</strong> – the net extends up to 1.7 m, no tools',
        '<strong>Everything included</strong> – 2 paddles and 6 balls in the set',
        '<strong>Leaves no marks</strong> – rubber-lined clamps fit tabletops up to 5 cm',
        '<strong>Stays put outdoors too</strong> – anti-slip rubber base',
        '<strong>Packed away in seconds</strong> – the net retracts and the whole set fits in the box',
      ],
      option: 'Colour', varden: ['Black', 'Orange'],
      alt: { main: 'Retractable table tennis net with two paddles and six balls', svart: 'The set with black net holders', orange: 'The set with orange net holders', info1: 'The net stretched across a full table', info2: 'The net extends to 1.7 m – anti-slip rubber base' },
    },
  },

  kangor: {
    no: {
      titel: 'Turstøvler Herre – Grep & Støtte på Stien',
      problemH: 'Lave sko tar slutt der stien begynner',
      problemP: 'Røtter, løse steiner og bratte svaberg – i tynne joggesko kjenner du hvert skarpe steg gjennom sålen, og på glatte røtter er det ankelen som får ta støyten.',
      losningH: 'Støvelen som er bygget for terrenget',
      losningP: 'Grov såle som biter i grus og berg, høyere skaft som støtter ankelen og metallhekter som gjør snøringen rask og stødig. Overdelen i semsket skinn og mesh holder vekten nede – støvelen henger med hele dagen uten å kjennes som støpejern.',
      bullets: [
        '<strong>Griper på grus, berg og våte røtter</strong> – grovt mønstret yttersåle',
        '<strong>Støtter ankelen i ulendt terreng</strong> – høyere skaft med polstret krage',
        '<strong>Snøringen sitter hele dagen</strong> – metallhekter i stedet for stoffhemper',
        '<strong>Tåler å bli dratt gjennom skogen</strong> – forsterket tåhette som tar støytene',
      ],
      option: 'Størrelse',
      alt: { main: 'Turstøvler herre i semsket skinn og mesh med grov såle', gaende: 'Støvlene i steget opp en steinete skogssti', miljo: 'Et par turstøvler på et svaberg ved stien' },
    },
    da: {
      titel: 'Vandrestøvler Herre – Greb & Støtte på Stien',
      problemH: 'Lave sko slipper op, hvor stien begynder',
      problemP: 'Rødder, løse sten og stejle klipper – i tynde sneakers mærker du hvert skarpt skridt gennem sålen, og på glatte rødder er det anklen, der tager imod.',
      losningH: 'Støvlen der er bygget til terrænet',
      losningP: 'Grov sål der bider i grus og klippe, højere skaft der støtter anklen og metalkroge der gør snøringen hurtig og stabil. Overdelen i ruskind og mesh holder vægten nede – støvlen følger med hele dagen uden at føles som støbejern.',
      bullets: [
        '<strong>Griber på grus, klippe og våde rødder</strong> – groft mønstret ydersål',
        '<strong>Støtter anklen i ujævnt terræn</strong> – højere skaft med polstret krave',
        '<strong>Snøringen sidder hele dagen</strong> – metalkroge i stedet for stofstropper',
        '<strong>Tåler at blive slæbt gennem skoven</strong> – forstærket tåkappe der tager stødene',
      ],
      option: 'Størrelse',
      alt: { main: 'Vandrestøvler herre i ruskind og mesh med grov sål', gaende: 'Støvlerne på vej op ad en stenet skovsti', miljo: 'Et par vandrestøvler på en klippe ved stien' },
    },
    fi: {
      titel: 'Vaelluskengät Miehille – Pito & Tuki Polulla',
      problemH: 'Matalat kengät loppuvat siihen, mistä polku alkaa',
      problemP: 'Juuret, irtokivet ja jyrkät kalliot – ohuissa lenkkareissa tunnet jokaisen terävän askeleen pohjan läpi, ja liukkailla juurilla nilkka ottaa vastaan.',
      losningH: 'Kenkä, joka on tehty maastoon',
      losningP: 'Karkea pohja pitää sorassa ja kalliolla, korkeampi varsi tukee nilkkaa ja metallikoukut tekevät nauhoituksesta nopean ja tukevan. Mokka- ja mesh-päällinen pitää painon kurissa – kenkä kulkee mukana koko päivän tuntumatta valuraudalta.',
      bullets: [
        '<strong>Pitää sorassa, kalliolla ja märillä juurilla</strong> – karkeakuvioinen ulkopohja',
        '<strong>Tukee nilkkaa epätasaisessa maastossa</strong> – korkeampi varsi ja pehmustettu kaulus',
        '<strong>Nauhat pysyvät koko päivän</strong> – metallikoukut kangaslenkkien sijaan',
        '<strong>Kestää metsässä</strong> – vahvistettu kärki ottaa kolhut vastaan',
      ],
      option: 'Koko',
      alt: { main: 'Miesten vaelluskengät mokkaa ja meshiä, karkea pohja', gaende: 'Kengät askeleessa kivisellä metsäpolulla', miljo: 'Vaelluskengät kalliolla polun vieressä' },
    },
    en: {
      titel: "Men's Hiking Boots – Grip & Support on the Trail",
      problemH: 'Low shoes give up where the trail begins',
      problemP: "Roots, loose rocks and steep slabs – in thin trainers you feel every sharp step through the sole, and on slippery roots it's your ankle that pays.",
      losningH: 'The boot built for the terrain',
      losningP: 'A chunky sole that bites into gravel and rock, a higher shaft that supports your ankle, and metal lacing hooks that make tightening quick and solid. The suede-and-mesh upper keeps the weight down – these boots keep up all day without feeling like cast iron.',
      bullets: [
        '<strong>Grips on gravel, rock and wet roots</strong> – deep-lug outsole',
        '<strong>Supports your ankle on rough ground</strong> – higher shaft with padded collar',
        '<strong>Laces stay put all day</strong> – metal hooks instead of fabric loops',
        '<strong>Built to be dragged through the woods</strong> – reinforced toe cap takes the knocks',
      ],
      option: 'Size',
      alt: { main: "Men's hiking boots in suede and mesh with a chunky sole", gaende: 'The boots mid-stride on a rocky forest trail', miljo: 'A pair of hiking boots on a rock beside the trail' },
    },
  },

  bollpannband: {
    no: {
      titel: 'Ballpannebånd – Kveldens Morsomste Duell',
      problemH: 'Alle sitter i hver sin sofa med hver sin skjerm',
      problemP: 'Fredagskosen er koselig på papiret – i virkeligheten scroller alle hver for seg. Og før hver bursdag samme jakt: en gave som ikke er nok et gavekort.',
      losningH: 'Ta på pannebåndet – og se hva som skjer',
      losningP: 'Ballen henger i en elastisk snor midt i pannen og spretter tilbake i retninger ingen hadde regnet med. Den som har båndet ser fjollete ut, resten ler, og to minutter senere står hele familien i kø for å slå rekorden. At det tilfeldigvis skjerper refleksene, er mest en unnskyldning for de voksne.',
      bullets: [
        '<strong>Får hele rommet til å le</strong> – den som bommer ser morsomst ut',
        '<strong>Alle kan være med med en gang</strong> – justerbart pannebånd, fra barnebursdag til slektsmiddag',
        '<strong>Konkurransen kommer av seg selv</strong> – tell treff på rad og kår en mester',
        '<strong>Forstyrrer ingen</strong> – myk skumball, ingen smell i gulv eller vegger',
        '<strong>Liten å pakke inn, lett å ta med</strong> – får plass i lomma og i gaveposen',
      ],
      option: 'Farge', varden: ['Svart', 'Rød'],
      alt: { main: 'Ballpannebåndet i full fart – ballen spretter tilbake mot pannen', produkt: 'Pannebåndet med elastisk snor og ball', detalj: 'Ballen i nærbilde midt i en duell', kvall: 'Ballpannebåndet på stuebordet en spillkveld' },
    },
    da: {
      titel: 'Boldpandebånd – Aftenens Sjoveste Duel',
      problemH: 'Alle sidder i hver sin sofa med hver sin skærm',
      problemP: 'Fredagshyggen er hyggelig på papiret – i virkeligheden scroller alle hver for sig. Og før hver fødselsdag samme jagt: en gave, der ikke er endnu et gavekort.',
      losningH: 'Tag pandebåndet på – og se hvad der sker',
      losningP: 'Bolden hænger i en elastisk snor midt i panden og hopper tilbage i retninger, ingen havde regnet med. Den der har båndet ser fjollet ud, resten griner, og to minutter senere står hele familien i kø for at slå rekorden. At det tilfældigvis skærper reflekserne, er mest en undskyldning for de voksne.',
      bullets: [
        '<strong>Får hele stuen til at grine</strong> – den der rammer forbi ser sjovest ud',
        '<strong>Alle kan være med med det samme</strong> – justerbart pandebånd, fra børnefødselsdag til familiemiddag',
        '<strong>Konkurrencen kommer af sig selv</strong> – tæl træffere i træk og kår en mester',
        '<strong>Forstyrrer ingen</strong> – blød skumbold, ingen smæld i gulv eller vægge',
        '<strong>Lille at pakke ind, let at tage med</strong> – kan være i lommen og i gaveposen',
      ],
      option: 'Farve', varden: ['Sort', 'Rød'],
      alt: { main: 'Boldpandebåndet i fuld fart – bolden hopper tilbage mod panden', produkt: 'Pandebåndet med elastisk snor og bold', detalj: 'Bolden i nærbillede midt i en duel', kvall: 'Boldpandebåndet på sofabordet en spilleaften' },
    },
    fi: {
      titel: 'Pallo-otsanauha – Illan Hauskin Kaksintaistelu',
      problemH: 'Kaikki istuvat omalla sohvallaan oman ruudun ääressä',
      problemP: 'Perjantai-ilta on mukava paperilla – todellisuudessa jokainen selaa omiaan. Ja ennen jokaisia syntymäpäiviä sama metsästys: lahja, joka ei ole taas yksi lahjakortti.',
      losningH: 'Laita otsanauha päähän – ja katso mitä tapahtuu',
      losningP: 'Pallo roikkuu joustavassa narussa keskellä otsaa ja kimpoaa takaisin suunnista, joita kukaan ei arvannut. Nauhan kantaja näyttää hassulta, muut nauravat, ja kahden minuutin päästä koko perhe jonottaa rikkomaan ennätystä. Se, että se sattuu terävöittämään refleksejä, on lähinnä aikuisten tekosyy.',
      bullets: [
        '<strong>Saa koko huoneen nauramaan</strong> – ohi lyövä näyttää hauskimmalta',
        '<strong>Kaikki mukaan heti</strong> – säädettävä otsanauha, lastenkutsuista sukujuhliin',
        '<strong>Kisa syntyy itsestään</strong> – laske peräkkäiset osumat ja kruunaa mestari',
        '<strong>Ei häiritse ketään</strong> – pehmeä vaahtomuovipallo, ei pauketta lattiaan tai seiniin',
        '<strong>Pieni paketoida, helppo ottaa mukaan</strong> – mahtuu taskuun ja lahjakassiin',
      ],
      option: 'Väri', varden: ['Musta', 'Punainen'],
      alt: { main: 'Pallo-otsanauha vauhdissa – pallo kimpoaa takaisin otsaa kohti', produkt: 'Otsanauha, joustava naru ja pallo', detalj: 'Pallo lähikuvassa kesken kaksintaistelun', kvall: 'Pallo-otsanauha sohvapöydällä peli-iltana' },
    },
    en: {
      titel: 'Headband Ball – The Funniest Duel of the Night',
      problemH: "Everyone's on their own sofa with their own screen",
      problemP: "A cosy night in sounds great on paper – in reality everyone's scrolling separately. And before every birthday, the same hunt: a present that isn't yet another gift card.",
      losningH: 'Put the headband on – and watch what happens',
      losningP: 'The ball hangs on an elastic string in the middle of your forehead and bounces back in directions nobody saw coming. Whoever wears the band looks ridiculous, everyone else laughs, and two minutes later the whole family is queueing to beat the record. The fact that it happens to sharpen your reflexes is mostly an excuse for the grown-ups.',
      bullets: [
        '<strong>Gets the whole room laughing</strong> – whoever misses looks the funniest',
        "<strong>Everyone can join in straight away</strong> – adjustable headband, from kids' parties to family dinners",
        '<strong>The competition starts itself</strong> – count hits in a row and crown a champion',
        '<strong>Disturbs nobody</strong> – soft foam ball, no thuds on floors or walls',
        '<strong>Small to wrap, easy to bring</strong> – fits in a pocket or a gift bag',
      ],
      option: 'Colour', varden: ['Black', 'Red'],
      alt: { main: 'The headband ball in action – the ball bouncing back', produkt: 'The headband with elastic string and ball', detalj: 'The ball up close mid-duel', kvall: 'The headband ball on the coffee table on games night' },
    },
  },

  batmotor: {
    no: {
      titel: 'Båtmotortrekk 420D – Heldekkende for Påhengsmotor',
      problemH: 'Snart står båten på land igjen – og motoren står ubeskyttet til våren',
      problemP: 'Regn, snø og frost jobber på påhengsmotoren i seks måneder. Og en blank motor på en opplagt båt er det første en tyv får øye på fra veien.',
      losningH: 'Et heldekkende vintertrekk for påhengsmotoren',
      losningP: 'Dra trekket over hele motoren – fra dekselet og ned over riggen – og stram remmen rundt midten. 420D Oxford-stoff holder vær og skitt ute gjennom hele opplaget, og en tildekket motor er et langt kjedeligere bytte enn en åpen.',
      bullets: [
        '<strong>Motoren overvintrer under tak</strong> – dekker fra deksel til rigg, ikke bare toppen',
        '<strong>Tåler en hel vinter ute</strong> – slitesterkt 420D Oxford-stoff mot regn, snø og UV',
        '<strong>Mindre fristende for tyven</strong> – ingen ser hvilken motor som står under',
        '<strong>Passer din motor</strong> – ni størrelser fra 0–5 hk til 250–350 hk, se måltabellen',
        '<strong>På før båten er surret fast</strong> – dras over og strammes, ingen verktøy',
      ],
      option: 'Motorstørrelse', hk: 'hk',
      alt: { main: 'Heldekkende båtmotortrekk i svart 420D Oxford', pabat: 'Trekket på en påhengsmotor ved opplagsplassen', tabell: 'Størrelsesguide – omkrets og høyde per motorstørrelse', vinter: 'Motortrekket på en liten aluminiumsbåt på henger' },
    },
    da: {
      titel: 'Bådmotorcover 420D – Heldækkende til Påhængsmotor',
      problemH: 'Snart står båden på land igen – og motoren står ubeskyttet til foråret',
      problemP: 'Regn, sne og frost arbejder på påhængsmotoren i seks måneder. Og en blank motor på en optaget båd er det første, en tyv får øje på fra vejen.',
      losningH: 'Et heldækkende vintercover til påhængsmotoren',
      losningP: 'Træk coveret over hele motoren – fra hjelmen og ned over rigget – og stram remmen om midten. 420D Oxford-stof holder vejr og snavs ude gennem hele vinteropbevaringen, og en tildækket motor er et langt kedeligere bytte end en åben.',
      bullets: [
        '<strong>Motoren overvintrer under tag</strong> – dækker fra hjelm til rig, ikke kun toppen',
        '<strong>Tåler en hel vinter ude</strong> – slidstærkt 420D Oxford-stof mod regn, sne og UV',
        '<strong>Mindre fristende for tyven</strong> – ingen kan se, hvilken motor der står under',
        '<strong>Passer til din motor</strong> – ni størrelser fra 0–5 hk til 250–350 hk, se måltabellen',
        '<strong>På før båden er surret fast</strong> – trækkes over og strammes, intet værktøj',
      ],
      option: 'Motorstørrelse', hk: 'hk',
      alt: { main: 'Heldækkende bådmotorcover i sort 420D Oxford', pabat: 'Coveret på en påhængsmotor ved vinteropbevaringen', tabell: 'Størrelsesguide – omkreds og højde per motorstørrelse', vinter: 'Motorcoveret på en lille aluminiumsbåd på trailer' },
    },
    fi: {
      titel: 'Perämoottorin Suoja 420D – Peittää Koko Moottorin',
      problemH: 'Pian vene on taas maissa – ja moottori seisoo suojaamatta kevääseen asti',
      problemP: 'Sade, lumi ja pakkanen kuluttavat perämoottoria kuusi kuukautta. Ja kiiltävä moottori talviteloilla olevassa veneessä on ensimmäinen asia, jonka varas huomaa tieltä.',
      losningH: 'Koko moottorin peittävä talvisuoja',
      losningP: 'Vedä suoja koko moottorin yli – kopasta rikiin asti – ja kiristä hihna keskeltä. 420D Oxford-kangas pitää sään ja lian ulkona koko säilytyksen ajan, ja peitetty moottori on varkaalle paljon tylsempi kohde kuin avoin.',
      bullets: [
        '<strong>Moottori talvehtii katon alla</strong> – peittää kopasta rikiin, ei vain yläosaa',
        '<strong>Kestää koko talven ulkona</strong> – kestävä 420D Oxford-kangas sadetta, lunta ja UV:ta vastaan',
        '<strong>Vähemmän houkutteleva varkaalle</strong> – kukaan ei näe, mikä moottori suojan alla on',
        '<strong>Sopii moottoriisi</strong> – yhdeksän kokoa, 0–5 hv … 250–350 hv, katso kokotaulukko',
        '<strong>Paikallaan hetkessä</strong> – vedetään päälle ja kiristetään, ei työkaluja',
      ],
      option: 'Moottorikoko', hk: 'hv',
      alt: { main: 'Koko moottorin peittävä suoja, musta 420D Oxford', pabat: 'Suoja perämoottorissa talvisäilytyspaikalla', tabell: 'Kokotaulukko – ympärys ja korkeus moottorikoon mukaan', vinter: 'Suoja pienen alumiiniveneen moottorissa trailerilla' },
    },
    en: {
      titel: 'Outboard Motor Cover 420D – Full Coverage',
      problemH: 'Soon the boat comes ashore again – and the motor sits exposed until spring',
      problemP: 'Rain, snow and frost work on your outboard for six months. And a shiny motor on a laid-up boat is the first thing a thief spots from the road.',
      losningH: 'A full-coverage winter cover for your outboard',
      losningP: 'Pull the cover over the entire motor – from the cowling down over the leg – and tighten the strap around the middle. 420D Oxford fabric keeps weather and grime out all through winter storage, and a covered motor is a far duller prize than an open one.',
      bullets: [
        '<strong>Your motor winters under cover</strong> – covers cowling to leg, not just the top',
        '<strong>Survives a whole winter outside</strong> – tough 420D Oxford fabric against rain, snow and UV',
        '<strong>Less tempting for thieves</strong> – nobody can see which motor sits underneath',
        '<strong>Fits your motor</strong> – nine sizes from 0–5 HP to 250–350 HP, see the size guide',
        "<strong>On before the boat's even strapped down</strong> – pull over and tighten, no tools",
      ],
      option: 'Motor size', hk: 'HP',
      alt: { main: 'Full-coverage outboard motor cover in black 420D Oxford', pabat: 'The cover on an outboard at the storage yard', tabell: 'Size guide – perimeter and height per motor size', vinter: 'The cover on a small aluminium boat on a trailer' },
    },
  },

  mc: {
    no: {
      titel: 'MC-Trekk 218×118 cm – Regn, Støv & UV',
      problemH: 'Lakken får gjennomgå hver natt den står ute',
      problemP: 'Regn, fugleskitt og sol jobber på sykkelen døgnet rundt. Etter en sesong utendørs synes det – matt lakk, rust på krommet.',
      losningH: 'Et skall som tar været i stedet',
      losningP: 'Trekket dras over på et minutt og dekker hele sykkelen, 218 × 118,5 cm. Regnet renner av, støvet blir liggende utenpå, og UV-strålene bleker trekket i stedet for lakken.',
      bullets: [
        '<strong>Lakken slipper regn og sol</strong> – vannavvisende materiale med UV-beskyttelse',
        '<strong>På og av på et minutt</strong> – lett materiale, ingen spenner å krangle med',
        '<strong>Sitter i vinden</strong> – strikk-kant rundt hele underkanten',
        '<strong>Dekker hele sykkelen</strong> – 218 × 118,5 cm, passer de fleste motorsykler og elsykler',
        '<strong>Blir med på turen</strong> – brettes sammen til en liten pakke',
      ],
      alt: { studio: 'Trekket over en motorsykkel – bakhjulet fritt', regn: 'Regnet perler på trekket', matt: 'Målskisse – 218 × 118,5 cm', resar: 'Strikk-kanten som holder trekket på plass' },
    },
    da: {
      titel: 'MC-Cover 218×118 cm – Regn, Støv & UV',
      problemH: 'Lakken står for skud hver nat, den holder ude',
      problemP: 'Regn, fugleklatter og sol arbejder på cyklen døgnet rundt. Efter en sæson udenfor kan det ses – mat lak, rust på krommet.',
      losningH: 'En skal der tager vejret i stedet',
      losningP: 'Coveret trækkes over på et minut og dækker hele cyklen, 218 × 118,5 cm. Regnen løber af, støvet bliver liggende udenpå, og UV-strålerne bleger coveret i stedet for lakken.',
      bullets: [
        '<strong>Lakken slipper for regn og sol</strong> – vandafvisende materiale med UV-beskyttelse',
        '<strong>På og af på et minut</strong> – let materiale, ingen spænder at bøvle med',
        '<strong>Bliver siddende i blæsten</strong> – elastikkant hele vejen rundt forneden',
        '<strong>Dækker hele cyklen</strong> – 218 × 118,5 cm, passer de fleste motorcykler og elcykler',
        '<strong>Med på turen</strong> – foldes sammen til en lille pakke',
      ],
      alt: { studio: 'Coveret over en motorcykel – baghjulet frit', regn: 'Regnen perler på coveret', matt: 'Målskitse – 218 × 118,5 cm', resar: 'Elastikkanten der holder coveret på plads' },
    },
    fi: {
      titel: 'Moottoripyörän Suojapeite 218×118 cm – Sade, Pöly & UV',
      problemH: 'Maali kärsii joka yö, jonka pyörä seisoo ulkona',
      problemP: 'Sade, linnunjätökset ja aurinko kuluttavat pyörää vuorokauden ympäri. Yhden ulkokauden jälkeen sen näkee – himmeä maali, ruostetta kromissa.',
      losningH: 'Kuori, joka ottaa sään vastaan',
      losningP: 'Peite vedetään päälle minuutissa ja se peittää koko pyörän, 218 × 118,5 cm. Sade valuu pois, pöly jää pintaan ja UV-säteet haalistavat peitettä maalin sijaan.',
      bullets: [
        '<strong>Maali säästyy sateelta ja auringolta</strong> – vettä hylkivä materiaali, UV-suoja',
        '<strong>Päälle ja pois minuutissa</strong> – kevyt materiaali, ei solkia',
        '<strong>Pysyy tuulessa</strong> – kuminauhareunus koko alareunassa',
        '<strong>Peittää koko pyörän</strong> – 218 × 118,5 cm, sopii useimpiin moottoripyöriin ja sähköpyöriin',
        '<strong>Mukaan matkalle</strong> – taittuu pieneksi paketiksi',
      ],
      alt: { studio: 'Peite moottoripyörän päällä – takapyörä vapaana', regn: 'Sade helmeilee peitteen pinnalla', matt: 'Mittakuva – 218 × 118,5 cm', resar: 'Kuminauhareunus pitää peitteen paikallaan' },
    },
    en: {
      titel: 'Motorcycle Cover 218×118 cm – Rain, Dust & UV',
      problemH: 'The paintwork takes a beating every night it stands outside',
      problemP: 'Rain, bird droppings and sun work on your bike around the clock. After one season outdoors it shows – dull paint, rust on the chrome.',
      losningH: 'A shell that takes the weather instead',
      losningP: 'The cover pulls on in a minute and covers the whole bike, 218 × 118.5 cm. Rain runs off, dust stays on the outside, and the UV bleaches the cover instead of your paint.',
      bullets: [
        '<strong>Your paint skips the rain and sun</strong> – water-repellent material with UV protection',
        '<strong>On and off in a minute</strong> – light material, no buckles to fight with',
        '<strong>Stays put in the wind</strong> – elastic hem all the way round',
        '<strong>Covers the whole bike</strong> – 218 × 118.5 cm, fits most motorcycles and e-bikes',
        '<strong>Comes along on trips</strong> – folds down to a small pack',
      ],
      alt: { studio: 'The cover over a motorcycle – rear wheel free', regn: 'Rain beading on the cover', matt: 'Dimensions – 218 × 118.5 cm', resar: 'The elastic hem that keeps the cover in place' },
    },
  },

  dorr: {
    no: {
      problemH: 'Gulvtrekken finner alltid veien inn under døren',
      problemP: 'Sprekken under døren slipper inn kald luft, korridorlyd og støv – og varmen du betaler for smetter ut samme vei.',
      losningH: 'En list som klippes til din dør og tetter sprekken',
      losningP: 'Fest den selvklebende borrelåsen langs dørens underkant, klipp listen til riktig bredde med en vanlig saks og trykk den fast. Skumsylinderen legger seg tett mot gulvet – og følger med døren hver gang den åpnes og lukkes.',
      bullets: [
        '<strong>Trekken blir stående utenfor</strong> – skumsylinderen slutter tett mot gulvet',
        '<strong>Naboens lyd dempes</strong> – sprekken lyden lekker gjennom forsvinner',
        '<strong>Klippes til din dør</strong> – 94 cm lang, kappes med en vanlig saks',
        '<strong>Sitter uten verktøy</strong> – selvklebende borrelås, ingen skruer',
        '<strong>Følger døren</strong> – åpne og lukk som vanlig, listen blir med',
      ],
      alt: { huvud: 'Listen montert på dørens underkant', padorr: 'Listen på en hvit innerdør', matt: 'Målbilde – 94 cm lang, 3 cm skumsylinder, 8 cm klaff', rulle: 'Listen sammenrullet med borrelåsen synlig', klipp: 'Listen klippes til riktig bredde med saks', skum: 'Skumsylinderen i nærbilde' },
    },
    da: {
      problemH: 'Gulvtrækken finder altid vej ind under døren',
      problemP: 'Sprækken under døren lukker kold luft, lyd fra opgangen og støv ind – og varmen du betaler for smutter ud samme vej.',
      losningH: 'En liste der klippes til din dør og lukker sprækken',
      losningP: 'Sæt den selvklæbende velcrostrimmel fast langs dørens underkant, klip listen til i bredden med en almindelig saks og tryk den på. Skumcylinderen lægger sig tæt mod gulvet – og følger med døren, hver gang den åbnes og lukkes.',
      bullets: [
        '<strong>Trækken bliver udenfor</strong> – skumcylinderen slutter tæt mod gulvet',
        '<strong>Naboens støj dæmpes</strong> – sprækken lyden siver igennem forsvinder',
        '<strong>Klippes til din dør</strong> – 94 cm lang, klippes med en almindelig saks',
        '<strong>Sidder fast uden værktøj</strong> – selvklæbende velcro, ingen skruer',
        '<strong>Følger døren</strong> – åbn og luk som normalt, listen følger med',
      ],
      alt: { huvud: 'Listen monteret på dørens underkant', padorr: 'Listen på en hvid indvendig dør', matt: 'Målbillede – 94 cm lang, 3 cm skumcylinder, 8 cm flap', rulle: 'Listen rullet sammen med velcroen synlig', klipp: 'Listen klippes til i bredden med en saks', skum: 'Skumcylinderen i nærbillede' },
    },
    fi: {
      problemH: 'Veto löytää aina tiensä oven alta',
      problemP: 'Oven alla oleva rako päästää sisään kylmää ilmaa, käytävän äänet ja pölyn – ja lämpö, josta maksat, karkaa samaa reittiä.',
      losningH: 'Tiiviste, joka leikataan oveesi sopivaksi',
      losningP: 'Kiinnitä itsekiinnittyvä tarranauha oven alareunaan, leikkaa tiiviste oikeaan leveyteen tavallisilla saksilla ja paina se paikalleen. Vaahtomuovirulla asettuu tiiviisti lattiaa vasten – ja kulkee oven mukana joka avauksella.',
      bullets: [
        '<strong>Veto jää ulkopuolelle</strong> – vaahtomuovirulla sulkee raon lattiaa vasten',
        '<strong>Naapurin äänet vaimenevat</strong> – rako, josta ääni vuotaa, katoaa',
        '<strong>Leikataan oveesi</strong> – 94 cm pitkä, lyhenee tavallisilla saksilla',
        '<strong>Kiinni ilman työkaluja</strong> – itsekiinnittyvä tarranauha, ei ruuveja',
        '<strong>Kulkee oven mukana</strong> – avaa ja sulje normaalisti, tiiviste pysyy',
      ],
      alt: { huvud: 'Tiiviste asennettuna oven alareunaan', padorr: 'Tiiviste valkoisessa sisäovessa', matt: 'Mittakuva – 94 cm pitkä, 3 cm vaahtomuovi, 8 cm läppä', rulle: 'Tiiviste rullalla, tarranauha näkyvissä', klipp: 'Tiiviste leikataan saksilla oikeaan leveyteen', skum: 'Vaahtomuovirulla lähikuvassa' },
    },
    en: {
      problemH: 'The draught always finds its way under the door',
      problemP: "The gap under the door lets in cold air, hallway noise and dust – and the heat you pay for slips out the same way.",
      losningH: 'A seal you cut to fit your door',
      losningP: 'Stick the self-adhesive hook-and-loop strip along the bottom edge of the door, cut the seal to width with ordinary scissors and press it on. The foam cylinder sits tight against the floor – and moves with the door every time it opens and closes.',
      bullets: [
        '<strong>The draught stays outside</strong> – the foam cylinder seals tight against the floor',
        "<strong>The neighbours' noise fades</strong> – the gap the sound leaks through disappears",
        '<strong>Cut to fit your door</strong> – 94 cm long, trims with ordinary scissors',
        '<strong>Stays on without tools</strong> – self-adhesive hook-and-loop, no screws',
        '<strong>Moves with the door</strong> – open and close as usual, the seal comes along',
      ],
      alt: { huvud: 'The seal fitted to the bottom of a door', padorr: 'The seal on a white interior door', matt: 'Dimensions – 94 cm long, 3 cm foam cylinder, 8 cm flap', rulle: 'The seal rolled up with the hook-and-loop visible', klipp: 'The seal being cut to width with scissors', skum: 'The foam cylinder up close' },
    },
  },

  kran: {
    no: {
      problemH: 'En sprukket vannledning oppdages alltid for sent',
      problemP: 'Den første skikkelige kuldeperioden fryser vannet i utekranen. Isen sprenger kran eller ledning – og skaden synes først når alt tiner og lekker.',
      losningH: 'En vinterjakke for kranen',
      losningP: 'Trekk beskytteren over kranen og stram til – det isolerende fôret holder frosten ute hele vinteren. 420D Oxford-stoff på utsiden tåler snø, regn og is.',
      bullets: [
        '<strong>Kranen takler kuldeperiodene</strong> – tykt isolerende fôr holder frosten ute',
        '<strong>Sitter på hele vinteren</strong> – stropp som slutter tett rundt røret',
        '<strong>Tåler vær i månedsvis</strong> – slitesterkt 420D Oxford-stoff',
        '<strong>Montert på ti sekunder</strong> – trekkes over kranen, ingen verktøy',
        '<strong>Rommeligere enn de fleste</strong> – 22 × 14 cm, når helt inn til veggen',
      ],
      alt: { pakran: 'Kranbeskytteren på plass over utekranen', matt: 'Størrelsesbilde – 22 × 14 cm', studio: 'Kranbeskytteren i 420D Oxford-stoff' },
    },
    da: {
      problemH: 'Et sprængt vandrør opdages altid for sent',
      problemP: 'Den første rigtige kuldeperiode fryser vandet i udehanen. Isen sprænger hane eller rør – og skaden ses først, når det hele tør op og lækker.',
      losningH: 'En vinterjakke til hanen',
      losningP: 'Træk beskytteren over hanen og stram til – det isolerende foer holder frosten ude hele vinteren. 420D Oxford-stof på ydersiden tåler sne, regn og is.',
      bullets: [
        '<strong>Hanen klarer kuldeperioderne</strong> – tykt isolerende foer holder frosten ude',
        '<strong>Sidder på hele vinteren</strong> – strop der slutter tæt om røret',
        '<strong>Tåler vejr i månedsvis</strong> – slidstærkt 420D Oxford-stof',
        '<strong>Monteret på ti sekunder</strong> – trækkes over hanen, intet værktøj',
        '<strong>Rummeligere end de fleste</strong> – 22 × 14 cm, når helt ind til væggen',
      ],
      alt: { pakran: 'Hanebeskytteren på plads over udehanen', matt: 'Størrelsesbillede – 22 × 14 cm', studio: 'Hanebeskytteren i 420D Oxford-stof' },
    },
    fi: {
      problemH: 'Haljennut vesijohto huomataan aina liian myöhään',
      problemP: 'Ensimmäinen kunnon pakkasjakso jäädyttää veden ulkohanassa. Jää halkaisee hanan tai putken – ja vahinko näkyy vasta, kun kaikki sulaa ja vuotaa.',
      losningH: 'Talvitakki hanalle',
      losningP: 'Vedä suoja hanan yli ja kiristä – eristävä vuori pitää pakkasen loitolla koko talven. 420D Oxford-kangas kestää lunta, sadetta ja jäätä.',
      bullets: [
        '<strong>Hana kestää pakkasjaksot</strong> – paksu eristävä vuori pitää pakkasen ulkona',
        '<strong>Pysyy paikallaan koko talven</strong> – kiristysremmi sulkee tiiviisti putken ympärille',
        '<strong>Kestää säätä kuukausia</strong> – kestävä 420D Oxford-kangas',
        '<strong>Asennettu kymmenessä sekunnissa</strong> – vedetään hanan yli, ei työkaluja',
        '<strong>Tilavampi kuin useimmat</strong> – 22 × 14 cm, ulottuu seinään asti',
      ],
      alt: { pakran: 'Hanasuoja paikallaan ulkohanan päällä', matt: 'Kokokuva – 22 × 14 cm', studio: 'Hanasuoja 420D Oxford-kangasta' },
    },
    en: {
      problemH: 'A burst pipe is always discovered too late',
      problemP: 'The first real cold snap freezes the water in your outdoor tap. The ice cracks the tap or the pipe – and the damage only shows when it all thaws and leaks.',
      losningH: 'A winter jacket for your tap',
      losningP: 'Pull the cover over the tap and tighten – the insulating lining keeps the frost out all winter. 420D Oxford fabric on the outside handles snow, rain and ice.',
      bullets: [
        '<strong>Your tap rides out the cold snaps</strong> – thick insulating lining keeps the frost out',
        '<strong>Stays on all winter</strong> – strap that closes tight around the pipe',
        '<strong>Handles months of weather</strong> – tough 420D Oxford fabric',
        '<strong>Fitted in ten seconds</strong> – pulls over the tap, no tools',
        '<strong>Roomier than most</strong> – 22 × 14 cm, reaches right up to the wall',
      ],
      alt: { pakran: 'The tap cover in place over an outdoor tap', matt: 'Size image – 22 × 14 cm', studio: 'The tap cover in 420D Oxford fabric' },
    },
  },

  plysch: {
    no: {
      problemH: 'Kalde gulv vinner hver vintermorgen',
      problemP: 'Gulvvarmen når ikke helt frem, og sokker hjelper bare en stund. Føttene er kalde før kaffen er ferdig.',
      losningH: 'Tøfler fôret som en vinterjakke',
      losningP: 'Tykk plysj hele veien rundt foten holder varmen på plass, og TPR-sålen gjør at du kan gå ut med søpla uten å bytte sko.',
      bullets: [
        '<strong>Føttene holder seg varme</strong> – tykt plysjfôr rundt hele foten',
        '<strong>Funker også på oppkjørselen</strong> – slitesterk TPR-såle for inne og ute',
        '<strong>Ingenting å krangle med</strong> – slip-on, rett i om morgenen',
        '<strong>Sklir ikke i trappen</strong> – mønstret såle med grep',
        '<strong>Svikter under hælen</strong> – innersåle i memoryskum som former seg etter foten',
      ],
      alt: { studio: 'Tøflene i svart med plysjfôr', memory: 'Innersåle i memoryskum', anv: 'Tøflene i bruk hjemme', anv2: 'Tøflene på føttene ved sofaen' },
    },
    da: {
      problemH: 'Kolde gulve vinder hver vintermorgen',
      problemP: 'Gulvvarmen når ikke helt ud, og sokker hjælper kun et stykke tid. Fødderne er kolde, før kaffen er klar.',
      losningH: 'Hjemmesko foret som en vinterjakke',
      losningP: 'Tyk plys hele vejen rundt om foden holder varmen inde, og TPR-sålen gør, at du kan gå ud med skraldet uden at skifte sko.',
      bullets: [
        '<strong>Fødderne holder sig varme</strong> – tykt plysfoer rundt om hele foden',
        '<strong>Virker også i indkørslen</strong> – slidstærk TPR-sål til inde og ude',
        '<strong>Intet bøvl</strong> – slip-on, lige i om morgenen',
        '<strong>Skrider ikke på trappen</strong> – mønstret sål med greb',
        '<strong>Giver efter under hælen</strong> – indersål i memoryskum der former sig efter foden',
      ],
      alt: { studio: 'Hjemmeskoene i sort med plysfoer', memory: 'Indersål i memoryskum', anv: 'Hjemmeskoene i brug derhjemme', anv2: 'Hjemmeskoene på fødderne ved sofaen' },
    },
    fi: {
      problemH: 'Kylmät lattiat voittavat joka talviaamu',
      problemP: 'Lattialämmitys ei yletä kaikkialle, ja sukat auttavat vain hetken. Jalat ovat kylmät ennen kuin kahvi on valmista.',
      losningH: 'Tossut, jotka on vuorattu kuin talvitakki',
      losningP: 'Paksu plyysi koko jalan ympärillä pitää lämmön tallessa, ja TPR-pohjan ansiosta voit viedä roskat ulos vaihtamatta kenkiä.',
      bullets: [
        '<strong>Jalat pysyvät lämpiminä</strong> – paksu plyysivuori koko jalan ympärillä',
        '<strong>Toimii myös pihalla</strong> – kestävä TPR-pohja sisä- ja ulkokäyttöön',
        '<strong>Ei säätämistä</strong> – slip-on, suoraan jalkaan aamulla',
        '<strong>Ei luista portaissa</strong> – kuvioitu pohja pitää',
        '<strong>Joustaa kantapään alla</strong> – memory-vaahtopohjallinen muotoutuu jalan mukaan',
      ],
      alt: { studio: 'Mustat tossut plyysivuorilla', memory: 'Memory-vaahtopohjallinen', anv: 'Tossut käytössä kotona', anv2: 'Tossut jalassa sohvan vieressä' },
    },
    en: {
      problemH: 'Cold floors win every winter morning',
      problemP: "The underfloor heating never quite reaches, and socks only help for a while. Your feet are cold before the coffee's ready.",
      losningH: 'Slippers lined like a winter jacket',
      losningP: 'Thick plush all the way around your foot keeps the warmth in, and the TPR sole means you can take the bins out without changing shoes.',
      bullets: [
        '<strong>Your feet stay warm</strong> – thick plush lining all around the foot',
        '<strong>Works on the driveway too</strong> – durable TPR sole for indoors and out',
        '<strong>Nothing to fiddle with</strong> – slip-on, straight in every morning',
        "<strong>Won't slip on the stairs</strong> – patterned sole with grip",
        '<strong>Gives under your heel</strong> – memory foam insole that moulds to your foot',
      ],
      alt: { studio: 'The slippers in black with plush lining', memory: 'Memory foam insole', anv: 'The slippers in use at home', anv2: 'The slippers on feet by the sofa' },
    },
  },
};

export const PRISER = {
  pingis: { NO: '349.00', DK: '229.00', FI: '29.90', UK: '22.99' },
  kangor: { NO: '789.00', DK: '519.00', FI: '67.90', UK: '51.99' },
  bollpannband: { NO: '199.00', DK: '129.00', FI: '16.90', UK: '12.99' },
  batmotor: { NO: '529.00', DK: '439.00', FI: '60.90', UK: '35.99' },
  mc: { NO: '269.00', DK: '259.00', FI: '36.90', UK: '17.99' },
  dorr: { NO: '239.00', DK: '239.00', FI: '33.90', UK: '15.99' },
  kran: { NO: '219.00', DK: '229.00', FI: '30.90', UK: '14.99' },
  plysch: { NO: '369.00', DK: '279.00', FI: '45.90', UK: '29.99' },
};

export const HKSTORLEKAR = ['0–5', '6–15', '15–20', '20–30', '30–60', '60–100', '100–150', '175–225', '250–350'];
export const HKSKU = ['0-5', '6-15', '15-20', '20-30', '30-60', '60-100', '100-150', '175-225', '250-350'];
export const SKOSTORLEKAR = ['40', '41', '42', '43', '44', '45', '46'];
