// Offert 4 (2026-08-25): copy för 6 produkter × 5 språk (sv/no/da/fi/en).
// Skriven enligt butikens playbook: 7-block, utfallet först i bullets (och?-testet),
// inga hastighets- eller absolutlöften, alla räkneord ur CWD-offerten och
// referensbilderna. Gravstenspennan är medvetet lågmäld — det är en sorgprodukt.
// Badshortsen: copy klar men produkten skapas först när CWD bekräftat storlekarna.

export const GARANTI4 = {
  sv: '30 dagars öppet köp – gillar du det inte får du pengarna tillbaka. Smidig leverans och trygg betalning med Klarna. 🦫',
  no: '30 dagers åpent kjøp – liker du det ikke, får du pengene tilbake. Smidig levering og trygg betaling med Klarna. 🦫',
  da: '30 dages fuld returret – kan du ikke lide det, får du pengene tilbage. Smidig levering og tryg betaling med Klarna. 🦫',
  fi: '30 päivän palautusoikeus – jos et pidä siitä, saat rahasi takaisin. Sujuva toimitus ja turvallinen maksu Klarnalla. 🦫',
  en: "30-day returns – if you don't love it, you get your money back. Smooth delivery and secure payment with Klarna. 🦫",
};

export const RUBRIKER4 = {
  sv: { funktioner: 'Funktioner', garanti: 'Vår garanti' },
  no: { funktioner: 'Funksjoner', garanti: 'Vår garanti' },
  da: { funktioner: 'Funktioner', garanti: 'Vores garanti' },
  fi: { funktioner: 'Ominaisuudet', garanti: 'Takuumme' },
  en: { funktioner: 'Features', garanti: 'Our guarantee' },
};

export const T4 = {
  tankoverdrag: {
    sv: {
      titel: 'IBC-tanköverdrag 1000 L – Stoppar Alger & UV',
      problemH: 'Regnvattnet grönskar innan sommaren ens börjat',
      problemP: 'Solljus rakt in i tanken får alger att växa i vattnet, och UV-strålningen gör plasten spröd år för år. Presenningen som skulle skydda blåser av vid första höststormen.',
      losningH: 'Ett överdrag som håller ljuset ute och tanken hel',
      losningP: 'Trä överdraget över tanken och stäng dragkedjan – det gröna 210D-oxfordtyget stänger ute ljuset så algerna aldrig kommer igång, och tar solen i stället för plasten. Öppningen upptill gör att du kommer åt locket utan att ta av något, och måtten 120 × 100 × 116 cm passar en standardtank på 1000 liter.',
      bullets: [
        '<strong>Vattnet håller sig klart</strong> – tyget stänger ute ljuset som får alger att växa',
        '<strong>Tanken åldras inte i solen</strong> – 210D oxfordtyg tar UV-strålningen i stället för plasten',
        '<strong>Locket alltid åtkomligt</strong> – öppning upptill, fyll på utan att ta av överdraget',
        '<strong>På och av med dragkedja</strong> – ingen kamp med presenning och gummiband',
        '<strong>Passar standardtanken</strong> – 120 × 100 × 116 cm för 1000-liters IBC',
      ],
      alt: { main: 'Grönt IBC-tanköverdrag med dragkedja, öppning vid kranen', ute: 'Överdraget på en IBC-tank utomhus vid husväggen', matt: 'Måttbild – 120 × 100 × 116 cm, passar 1000-liters IBC-tank', forefter: 'Före och efter – IBC-tank utan och med överdrag', hog: 'Överdraget på en upphöjd IBC-tank' },
    },
    no: {
      titel: 'IBC-tanktrekk 1000 L – Stopper Alger & UV',
      problemH: 'Regnvannet grønnes før sommeren har begynt',
      problemP: 'Sollys rett inn i tanken får alger til å vokse i vannet, og UV-strålingen gjør plasten sprø år for år. Presenningen som skulle beskytte, blåser av i første høststorm.',
      losningH: 'Et trekk som holder lyset ute og tanken hel',
      losningP: 'Trekk det over tanken og lukk glidelåsen – det grønne 210D-oxfordstoffet stenger lyset ute så algene aldri kommer i gang, og tar solen i stedet for plasten. Åpningen på toppen gjør at du når lokket uten å ta av noe, og målene 120 × 100 × 116 cm passer en standardtank på 1000 liter.',
      bullets: [
        '<strong>Vannet holder seg klart</strong> – stoffet stenger ute lyset som får alger til å vokse',
        '<strong>Tanken eldes ikke i solen</strong> – 210D oxfordstoff tar UV-strålingen i stedet for plasten',
        '<strong>Lokket alltid tilgjengelig</strong> – åpning på toppen, fyll på uten å ta av trekket',
        '<strong>På og av med glidelås</strong> – ingen kamp med presenning og strikk',
        '<strong>Passer standardtanken</strong> – 120 × 100 × 116 cm for 1000-liters IBC',
      ],
      alt: { main: 'Grønt IBC-tanktrekk med glidelås og åpning ved kranen', ute: 'Trekket på en IBC-tank utendørs ved husveggen', matt: 'Målbilde – 120 × 100 × 116 cm, passer 1000-liters IBC-tank', forefter: 'Før og etter – IBC-tank uten og med trekk', hog: 'Trekket på en opphøyd IBC-tank' },
    },
    da: {
      titel: 'IBC-tankovertræk 1000 L – Stopper Alger & UV',
      problemH: 'Regnvandet bliver grønt, før sommeren er begyndt',
      problemP: 'Sollys direkte ind i tanken får alger til at vokse i vandet, og UV-strålingen gør plasten skør år for år. Presenningen, der skulle beskytte, blæser af i den første efterårsstorm.',
      losningH: 'Et overtræk der holder lyset ude og tanken hel',
      losningP: 'Træk det over tanken og luk lynlåsen – det grønne 210D-oxfordstof lukker lyset ude, så algerne aldrig kommer i gang, og tager solen i stedet for plasten. Åbningen i toppen gør, at du kan nå dækslet uden at tage noget af, og målene 120 × 100 × 116 cm passer til en standardtank på 1000 liter.',
      bullets: [
        '<strong>Vandet holder sig klart</strong> – stoffet lukker lyset ude, som får alger til at vokse',
        '<strong>Tanken ældes ikke i solen</strong> – 210D oxfordstof tager UV-strålingen i stedet for plasten',
        '<strong>Dækslet altid tilgængeligt</strong> – åbning i toppen, fyld på uden at tage overtrækket af',
        '<strong>På og af med lynlås</strong> – ingen kamp med presenning og elastikker',
        '<strong>Passer til standardtanken</strong> – 120 × 100 × 116 cm til 1000-liters IBC',
      ],
      alt: { main: 'Grønt IBC-tankovertræk med lynlås og åbning ved hanen', ute: 'Overtrækket på en IBC-tank udendørs ved husmuren', matt: 'Målbillede – 120 × 100 × 116 cm, passer til 1000-liters IBC-tank', forefter: 'Før og efter – IBC-tank uden og med overtræk', hog: 'Overtrækket på en hævet IBC-tank' },
    },
    fi: {
      titel: 'IBC-säiliön Suoja 1000 L – Estää Levän & UV:n',
      problemH: 'Sadevesi vihertyy ennen kuin kesä on edes alkanut',
      problemP: 'Suoraan säiliöön pääsevä auringonvalo kasvattaa levää veteen, ja UV-säteily haurastuttaa muovia vuosi vuodelta. Suojaksi tarkoitettu pressu lähtee ensimmäisessä syysmyrskyssä.',
      losningH: 'Suoja, joka pitää valon ulkona ja säiliön ehjänä',
      losningP: 'Vedä suoja säiliön päälle ja sulje vetoketju – vihreä 210D Oxford-kangas sulkee valon ulos, jolloin levä ei pääse alkuun, ja ottaa auringon vastaan muovin sijasta. Yläaukon kautta pääset korkkiin ottamatta mitään pois, ja mitat 120 × 100 × 116 cm sopivat tavalliseen 1000 litran säiliöön.',
      bullets: [
        '<strong>Vesi pysyy kirkkaana</strong> – kangas sulkee ulos valon, joka kasvattaa levää',
        '<strong>Säiliö ei vanhene auringossa</strong> – 210D Oxford-kangas ottaa UV-säteilyn muovin sijaan',
        '<strong>Korkki aina ulottuvilla</strong> – yläaukko, täytä ottamatta suojaa pois',
        '<strong>Päälle ja pois vetoketjulla</strong> – ei taistelua pressun ja kuminauhojen kanssa',
        '<strong>Sopii vakiosäiliöön</strong> – 120 × 100 × 116 cm, 1000 litran IBC',
      ],
      alt: { main: 'Vihreä IBC-säiliön suoja vetoketjulla, aukko hanan kohdalla', ute: 'Suoja IBC-säiliössä ulkona talon seinustalla', matt: 'Mittakuva – 120 × 100 × 116 cm, sopii 1000 litran IBC-säiliöön', forefter: 'Ennen ja jälkeen – IBC-säiliö ilman suojaa ja suojan kanssa', hog: 'Suoja korotetussa IBC-säiliössä' },
    },
    en: {
      titel: 'IBC Tank Cover 1000 L – Stops Algae & UV',
      problemH: 'The rainwater turns green before summer even starts',
      problemP: 'Sunlight straight into the tank grows algae in the water, and UV makes the plastic brittle year by year. The tarp that was meant to protect it blows off in the first autumn storm.',
      losningH: 'A cover that keeps the light out and the tank whole',
      losningP: 'Pull the cover over the tank and close the zip – the green 210D Oxford fabric shuts out the light so algae never get started, and takes the sun instead of the plastic. The top opening lets you reach the lid without removing anything, and at 120 × 100 × 116 cm it fits a standard 1000-litre tank.',
      bullets: [
        '<strong>The water stays clear</strong> – the fabric shuts out the light that grows algae',
        '<strong>The tank stops ageing in the sun</strong> – 210D Oxford fabric takes the UV instead of the plastic',
        '<strong>The lid stays reachable</strong> – top opening, refill without taking the cover off',
        '<strong>On and off with a zip</strong> – no wrestling with tarps and bungee cords',
        '<strong>Fits the standard tank</strong> – 120 × 100 × 116 cm for a 1000-litre IBC',
      ],
      alt: { main: 'Green IBC tank cover with zip and tap opening', ute: 'The cover on an IBC tank outdoors by a wall', matt: 'Dimensions – 120 × 100 × 116 cm, fits a 1000-litre IBC tank', forefter: 'Before and after – IBC tank without and with the cover', hog: 'The cover on a raised IBC tank' },
    },
  },

  jattefotboll: {
    sv: {
      titel: 'Jättefotboll 60 cm – Uppblåsbar för Trädgård & Pool',
      problemH: 'Halva kalaset sitter still och tittar på',
      problemP: 'Trädgårdsspelen är samma varje sommar, och de minsta kommer aldrig åt bollen. Det som skulle bli lek slutar med att tre spelar och resten väntar.',
      losningH: 'En fotboll ingen kan missa',
      losningP: 'En boll på 60 centimeter ändrar hela spelet: alla träffar den, ingen är dålig och varje skott ser dramatiskt ut. Lätt nog för femåringen, stor nog att få de vuxna att springa. Blås upp den till poolen, stranden eller gräsmattan – och släpp ut luften när festen är slut.',
      bullets: [
        '<strong>Alla kan vara med direkt</strong> – 60 cm boll går inte att missa',
        '<strong>Mjuk att ta emot</strong> – lätt, luftfylld PVC i stället för hård boll',
        '<strong>Funkar överallt</strong> – pool, strand, gräsmatta och gympasal',
        '<strong>Liten när festen är slut</strong> – släpp ut luften och lägg den i förrådet',
      ],
      alt: { main: 'Jättefotboll 60 cm vid poolkanten', familj: 'Familj som spelar med jättefotbollen på gräsmattan', matt: 'Måttbild – bollen är 60 cm i diameter', strand: 'Jättefotbollen i luften på stranden', detalj: 'Detaljbilder – ventil, material och sömmar', hund: 'Jättefotbollen i full fart över gräsmattan' },
    },
    no: {
      titel: 'Kjempefotball 60 cm – Oppblåsbar for Hage & Basseng',
      problemH: 'Halve selskapet sitter stille og ser på',
      problemP: 'Hagelekene er de samme hver sommer, og de minste når aldri ballen. Det som skulle bli lek, ender med at tre spiller og resten venter.',
      losningH: 'En fotball ingen kan bomme på',
      losningP: 'En ball på 60 centimeter forandrer hele spillet: alle treffer den, ingen er dårlig, og hvert skudd ser dramatisk ut. Lett nok for femåringen, stor nok til å få de voksne til å løpe. Blås den opp ved bassenget, stranden eller plenen – og slipp ut luften når festen er over.',
      bullets: [
        '<strong>Alle kan være med med en gang</strong> – en 60 cm ball er umulig å bomme på',
        '<strong>Myk å ta imot</strong> – lett, luftfylt PVC i stedet for hard ball',
        '<strong>Funker overalt</strong> – basseng, strand, plen og gymsal',
        '<strong>Liten når festen er over</strong> – slipp ut luften og legg den i boden',
      ],
      alt: { main: 'Kjempefotball 60 cm ved bassengkanten', familj: 'Familie som spiller med kjempefotballen på plenen', matt: 'Målbilde – ballen er 60 cm i diameter', strand: 'Kjempefotballen i luften på stranden', detalj: 'Detaljbilder – ventil, materiale og sømmer', hund: 'Kjempefotballen i full fart over plenen' },
    },
    da: {
      titel: 'Kæmpefodbold 60 cm – Oppustelig til Have & Pool',
      problemH: 'Halvdelen af festen sidder stille og ser på',
      problemP: 'Havelegene er de samme hver sommer, og de mindste når aldrig bolden. Det, der skulle blive leg, ender med, at tre spiller og resten venter.',
      losningH: 'En fodbold ingen kan misse',
      losningP: 'En bold på 60 centimeter ændrer hele spillet: alle rammer den, ingen er dårlig, og hvert skud ser dramatisk ud. Let nok til femårige, stor nok til at få de voksne til at løbe. Pust den op ved poolen, stranden eller græsplænen – og luk luften ud, når festen er slut.',
      bullets: [
        '<strong>Alle kan være med med det samme</strong> – en 60 cm bold er umulig at misse',
        '<strong>Blød at tage imod</strong> – let, luftfyldt PVC i stedet for hård bold',
        '<strong>Virker overalt</strong> – pool, strand, græsplæne og gymnastiksal',
        '<strong>Lille når festen er slut</strong> – luk luften ud og læg den i skuret',
      ],
      alt: { main: 'Kæmpefodbold 60 cm ved poolkanten', familj: 'Familie der spiller med kæmpefodbolden på græsplænen', matt: 'Målbillede – bolden er 60 cm i diameter', strand: 'Kæmpefodbolden i luften på stranden', detalj: 'Detaljebilleder – ventil, materiale og syninger', hund: 'Kæmpefodbolden i fuld fart over græsplænen' },
    },
    fi: {
      titel: 'Jättijalkapallo 60 cm – Puhallettava Pihalle & Altaalle',
      problemH: 'Puolet juhlista istuu paikallaan katsomassa',
      problemP: 'Pihapelit ovat samat joka kesä, eivätkä pienimmät koskaan ehdi palloon. Leikiksi tarkoitettu peli päättyy siihen, että kolme pelaa ja loput odottavat.',
      losningH: 'Jalkapallo, josta kukaan ei voi ohittaa',
      losningP: '60-senttinen pallo muuttaa koko pelin: kaikki osuvat siihen, kukaan ei ole huono, ja jokainen laukaus näyttää dramaattiselta. Tarpeeksi kevyt viisivuotiaalle, tarpeeksi iso saamaan aikuisetkin juoksemaan. Puhalla se täyteen altaalla, rannalla tai nurmikolla – ja päästä ilmat pihalle, kun juhlat ovat ohi.',
      bullets: [
        '<strong>Kaikki pääsevät heti mukaan</strong> – 60 cm palloon on mahdoton olla osumatta',
        '<strong>Pehmeä ottaa vastaan</strong> – kevyt, ilmatäytteinen PVC kovan pallon sijaan',
        '<strong>Toimii kaikkialla</strong> – allas, ranta, nurmikko ja liikuntasali',
        '<strong>Pieni kun juhlat loppuvat</strong> – päästä ilmat ulos ja laita varastoon',
      ],
      alt: { main: 'Jättijalkapallo 60 cm altaan reunalla', familj: 'Perhe pelaamassa jättijalkapallolla nurmikolla', matt: 'Mittakuva – pallon halkaisija on 60 cm', strand: 'Jättijalkapallo ilmassa rannalla', detalj: 'Yksityiskohdat – venttiili, materiaali ja saumat', hund: 'Jättijalkapallo vauhdissa nurmikolla' },
    },
    en: {
      titel: 'Giant Football 60 cm – Inflatable for Garden & Pool',
      problemH: 'Half the party sits still and watches',
      problemP: 'The garden games are the same every summer, and the youngest never get near the ball. What was meant to be play ends with three playing and the rest waiting.',
      losningH: 'A football nobody can miss',
      losningP: "A 60-centimetre ball changes the whole game: everyone hits it, nobody's bad, and every shot looks dramatic. Light enough for a five-year-old, big enough to make the grown-ups run. Blow it up at the pool, the beach or the lawn – and let the air out when the party's over.",
      bullets: [
        '<strong>Everyone joins in straight away</strong> – a 60 cm ball is impossible to miss',
        '<strong>Soft to catch</strong> – light, air-filled PVC instead of a hard ball',
        '<strong>Works everywhere</strong> – pool, beach, lawn and sports hall',
        "<strong>Small when the party's over</strong> – let the air out and put it in the shed",
      ],
      alt: { main: 'Giant 60 cm football by the pool', familj: 'Family playing with the giant football on the lawn', matt: 'Dimensions – the ball is 60 cm across', strand: 'The giant football in the air at the beach', detalj: 'Detail shots – valve, material and seams', hund: 'The giant football at full speed across the lawn' },
    },
  },

  benskydd: {
    sv: {
      titel: 'Damasker Vandring – Håller Snö, Väta & Grus Ute',
      problemH: 'Blöta strumpor avgör turen före trötta ben',
      problemP: 'Snö nerifrån, blöt sly, grus som letar sig ner i kängan – det är sällan vädret som avbryter turen, utan det som tar sig in nedtill.',
      losningH: 'Damasker som stänger till mellan känga och knä',
      losningP: 'Kroka fast i snörningen, dra remmen under foten och slut kardborren runt benet – 44 centimeter skydd i 100 % polyester håller snö, väta och grus ute hela vägen upp. En storlek som justeras efter benet.',
      bullets: [
        '<strong>Strumporna håller sig torra</strong> – 44 cm högt skydd mot snö, väta och blöt sly',
        '<strong>Inget grus i kängorna</strong> – sluter tätt runt känga och ben',
        '<strong>Sitter kvar i steget</strong> – krok i snörningen, rem under foten, kardborre runt benet',
        '<strong>Syns i terrängen</strong> – gul, neongrön eller orange',
        '<strong>En storlek, justerbar</strong> – 44 cm hög, 43 cm omkrets, passar de flesta vuxna',
      ],
      option: 'Färg', varden: ['Gul', 'Neongrön', 'Orange'],
      alt: { main: 'Damasker i signalfärg över vandringskängor', matt: 'Måttbild – 44 cm höga, 43 cm omkrets, 100 % polyester', neon: 'Damaskerna i neonfärg', orange: 'Damaskerna i orange', spanne: 'Justerbart spänne och rem under kängan', karborre: 'Kardborrestängning på utsidan' },
    },
    no: {
      titel: 'Gamasjer Tur – Holder Snø, Væte & Grus Ute',
      problemH: 'Våte sokker avgjør turen før trøtte bein',
      problemP: 'Snø nedenfra, våt kratt, grus som finner veien ned i støvelen – det er sjelden været som avbryter turen, men det som kommer seg inn nede.',
      losningH: 'Gamasjer som lukker til mellom støvel og kne',
      losningP: 'Fest kroken i snøringen, dra remmen under foten og lukk borrelåsen rundt leggen – 44 centimeter beskyttelse i 100 % polyester holder snø, væte og grus ute hele veien opp. Én størrelse som justeres etter beinet.',
      bullets: [
        '<strong>Sokkene holder seg tørre</strong> – 44 cm høy beskyttelse mot snø, væte og vått kratt',
        '<strong>Ingen grus i støvlene</strong> – lukker tett rundt støvel og bein',
        '<strong>Sitter i steget</strong> – krok i snøringen, rem under foten, borrelås rundt leggen',
        '<strong>Synes i terrenget</strong> – gul, neongrønn eller oransje',
        '<strong>Én størrelse, justerbar</strong> – 44 cm høy, 43 cm omkrets, passer de fleste voksne',
      ],
      option: 'Farge', varden: ['Gul', 'Neongrønn', 'Oransje'],
      alt: { main: 'Gamasjer i signalfarge over turstøvler', matt: 'Målbilde – 44 cm høye, 43 cm omkrets, 100 % polyester', neon: 'Gamasjene i neonfarge', orange: 'Gamasjene i oransje', spanne: 'Justerbar spenne og rem under støvelen', karborre: 'Borrelåslukking på utsiden' },
    },
    da: {
      titel: 'Gamacher Vandring – Holder Sne, Væde & Grus Ude',
      problemH: 'Våde sokker afgør turen før trætte ben',
      problemP: 'Sne nedefra, vådt krat, grus der finder vej ned i støvlen – det er sjældent vejret, der afbryder turen, men det, der kommer ind forneden.',
      losningH: 'Gamacher der lukker til mellem støvle og knæ',
      losningP: 'Sæt krogen i snøringen, træk remmen under foden og luk velcroen om benet – 44 centimeter beskyttelse i 100 % polyester holder sne, væde og grus ude hele vejen op. Én størrelse der justeres efter benet.',
      bullets: [
        '<strong>Sokkerne holder sig tørre</strong> – 44 cm høj beskyttelse mod sne, væde og vådt krat',
        '<strong>Intet grus i støvlerne</strong> – lukker tæt om støvle og ben',
        '<strong>Sidder fast i skridtet</strong> – krog i snøringen, rem under foden, velcro om benet',
        '<strong>Ses i terrænet</strong> – gul, neongrøn eller orange',
        '<strong>Én størrelse, justerbar</strong> – 44 cm høj, 43 cm i omkreds, passer de fleste voksne',
      ],
      option: 'Farve', varden: ['Gul', 'Neongrøn', 'Orange'],
      alt: { main: 'Gamacher i signalfarve over vandrestøvler', matt: 'Målbillede – 44 cm høje, 43 cm i omkreds, 100 % polyester', neon: 'Gamacherne i neonfarve', orange: 'Gamacherne i orange', spanne: 'Justerbart spænde og rem under støvlen', karborre: 'Velcrolukning på ydersiden' },
    },
    fi: {
      titel: 'Säärystimet Vaellus – Pitää Lumen, Kosteuden & Soran Ulkona',
      problemH: 'Märät sukat päättävät retken ennen väsyneitä jalkoja',
      problemP: 'Lunta alhaalta, märkää risukkoa, soraa joka löytää tiensä kenkään – harvoin sää keskeyttää retken, vaan se mikä pääsee sisään alhaalta.',
      losningH: 'Säärystimet, jotka sulkevat välin kengästä polveen',
      losningP: 'Kiinnitä koukku nauhoitukseen, vedä remmi jalan alta ja sulje tarranauha säären ympärille – 44 senttiä suojaa 100 % polyesteriä pitää lumen, kosteuden ja soran ulkona koko matkalta. Yksi koko, joka säätyy jalan mukaan.',
      bullets: [
        '<strong>Sukat pysyvät kuivina</strong> – 44 cm korkea suoja lunta, kosteutta ja märkää risukkoa vastaan',
        '<strong>Ei soraa kenkiin</strong> – sulkeutuu tiiviisti kengän ja säären ympärille',
        '<strong>Pysyy paikallaan askeleessa</strong> – koukku nauhoitukseen, remmi jalan alle, tarranauha ympärille',
        '<strong>Näkyy maastossa</strong> – keltainen, neonvihreä tai oranssi',
        '<strong>Yksi säädettävä koko</strong> – 44 cm korkea, 43 cm ympärys, sopii useimmille aikuisille',
      ],
      option: 'Väri', varden: ['Keltainen', 'Neonvihreä', 'Oranssi'],
      alt: { main: 'Säärystimet huomiovärissä vaelluskenkien päällä', matt: 'Mittakuva – 44 cm korkeat, 43 cm ympärys, 100 % polyesteri', neon: 'Säärystimet neonvärissä', orange: 'Säärystimet oranssina', spanne: 'Säädettävä solki ja remmi kengän alla', karborre: 'Tarranauhakiinnitys ulkopuolella' },
    },
    en: {
      titel: 'Hiking Gaiters – Keep Snow, Wet & Grit Out',
      problemH: 'Wet socks end the hike before tired legs do',
      problemP: "Snow from below, wet brush, grit finding its way into your boot – it's rarely the weather that cuts the walk short, it's what gets in at the bottom.",
      losningH: 'Gaiters that seal the gap from boot to knee',
      losningP: 'Hook into the laces, pull the strap under your foot and close the velcro around your calf – 44 centimetres of 100% polyester keeps snow, wet and grit out all the way up. One size, adjusted to fit.',
      bullets: [
        '<strong>Your socks stay dry</strong> – 44 cm of protection against snow, wet and soaked brush',
        '<strong>No grit in your boots</strong> – seals tight around boot and leg',
        '<strong>Stays put on the move</strong> – lace hook, underfoot strap, velcro around the calf',
        '<strong>Visible in the terrain</strong> – yellow, neon green or orange',
        '<strong>One adjustable size</strong> – 44 cm tall, 43 cm around, fits most adults',
      ],
      option: 'Colour', varden: ['Yellow', 'Neon Green', 'Orange'],
      alt: { main: 'High-vis gaiters over hiking boots', matt: 'Dimensions – 44 cm tall, 43 cm around, 100% polyester', neon: 'The gaiters in neon', orange: 'The gaiters in orange', spanne: 'Adjustable buckle and underfoot strap', karborre: 'Velcro closure on the outside' },
    },
  },

  gravstenspenna: {
    sv: {
      titel: 'Gravstenspenna – Återställer Blekt Text på Sten',
      problemH: 'Inskriptionen bleknar långt före stenen',
      problemP: 'Väder och år sliter på förgyllningen, och till slut syns namnet knappt. Att låta en stenhuggare fylla i texten kostar tusenlappar – så många stenar står kvar med text som inte går att läsa.',
      losningH: 'Fyll i texten själv, bokstav för bokstav',
      losningP: 'En penna med oljebaserad, väderbeständig färg och fin spets, gjord för graverad text i sten. Följ bokstävernas spår i lugn takt – färgen torkar snabbt och tål regn och frost. Ett stilla arbete som gör stor skillnad nästa gång du besöker platsen.',
      bullets: [
        '<strong>Namnet går att läsa igen</strong> – täckande färg gjord för graverad sten',
        '<strong>Tål att stå ute</strong> – oljebaserad, väderbeständig färg som klarar regn och frost',
        '<strong>Lätt att arbeta noggrant</strong> – fin spets som följer bokstävernas spår',
        '<strong>Torr innan du går därifrån</strong> – färgen torkar snabbt utan rinningar',
        '<strong>Nyans efter stenen</strong> – guld, svart, vit, silver, röd eller blå, 20 ml per penna',
      ],
      option: 'Färg', varden: ['Guld', 'Svart', 'Vit', 'Silver', 'Röd', 'Blå'],
      alt: { main: 'Gravstenspennan fyller i förgylld text på våt sten', vattentat: 'Färgen är vattentät – pennan används i regn', matt: 'Måttbild – pennan är 14,3 cm lång, spets Ø 1,4 cm', forefter: 'Före och efter – blekt och ifylld inskription', guld: 'Pennan i guld', silver: 'Pennan i silver', svart: 'Pennan i svart', vit: 'Pennan i vit', rod: 'Pennan i rött' },
    },
    no: {
      titel: 'Gravsteinspenn – Gjenoppretter Blek Tekst på Stein',
      problemH: 'Inskripsjonen blekner lenge før steinen',
      problemP: 'Vær og år sliter på forgyllingen, og til slutt synes navnet knapt. Å la en steinhugger fylle i teksten koster tusenlapper – så mange steiner står igjen med tekst som ikke kan leses.',
      losningH: 'Fyll i teksten selv, bokstav for bokstav',
      losningP: 'En penn med oljebasert, værbestandig farge og fin spiss, laget for gravert tekst i stein. Følg bokstavenes spor i rolig takt – fargen tørker raskt og tåler regn og frost. Et stille arbeid som gjør stor forskjell neste gang du besøker stedet.',
      bullets: [
        '<strong>Navnet kan leses igjen</strong> – dekkende farge laget for gravert stein',
        '<strong>Tåler å stå ute</strong> – oljebasert, værbestandig farge som klarer regn og frost',
        '<strong>Lett å arbeide nøyaktig</strong> – fin spiss som følger bokstavenes spor',
        '<strong>Tørr før du går derfra</strong> – fargen tørker raskt uten renninger',
        '<strong>Nyanse etter steinen</strong> – gull, svart, hvit, sølv, rød eller blå, 20 ml per penn',
      ],
      option: 'Farge', varden: ['Gull', 'Svart', 'Hvit', 'Sølv', 'Rød', 'Blå'],
      alt: { main: 'Gravsteinspennen fyller i forgylt tekst på våt stein', vattentat: 'Fargen er vanntett – pennen brukes i regn', matt: 'Målbilde – pennen er 14,3 cm lang, spiss Ø 1,4 cm', forefter: 'Før og etter – blek og fylt inskripsjon', guld: 'Pennen i gull', silver: 'Pennen i sølv', svart: 'Pennen i svart', vit: 'Pennen i hvit', rod: 'Pennen i rød' },
    },
    da: {
      titel: 'Gravstenspen – Genopretter Falmet Tekst på Sten',
      problemH: 'Inskriptionen falmer længe før stenen',
      problemP: 'Vejr og år slider på forgyldningen, og til sidst kan navnet næsten ikke ses. At lade en stenhugger trække teksten op koster tusindvis – så mange sten står med tekst, der ikke kan læses.',
      losningH: 'Træk teksten op selv, bogstav for bogstav',
      losningP: 'En pen med oliebaseret, vejrbestandig farve og fin spids, lavet til graveret tekst i sten. Følg bogstavernes spor i roligt tempo – farven tørrer hurtigt og tåler regn og frost. Et stille arbejde, der gør stor forskel, næste gang du besøger stedet.',
      bullets: [
        '<strong>Navnet kan læses igen</strong> – dækkende farve lavet til graveret sten',
        '<strong>Tåler at stå ude</strong> – oliebaseret, vejrbestandig farve der klarer regn og frost',
        '<strong>Let at arbejde præcist</strong> – fin spids der følger bogstavernes spor',
        '<strong>Tør før du går derfra</strong> – farven tørrer hurtigt uden løbere',
        '<strong>Nuance efter stenen</strong> – guld, sort, hvid, sølv, rød eller blå, 20 ml pr. pen',
      ],
      option: 'Farve', varden: ['Guld', 'Sort', 'Hvid', 'Sølv', 'Rød', 'Blå'],
      alt: { main: 'Gravstenspennen trækker forgyldt tekst op på våd sten', vattentat: 'Farven er vandtæt – pennen bruges i regn', matt: 'Målbillede – pennen er 14,3 cm lang, spids Ø 1,4 cm', forefter: 'Før og efter – falmet og opfrisket inskription', guld: 'Pennen i guld', silver: 'Pennen i sølv', svart: 'Pennen i sort', vit: 'Pennen i hvid', rod: 'Pennen i rød' },
    },
    fi: {
      titel: 'Hautakivikynä – Palauttaa Haalistuneen Tekstin',
      problemH: 'Kaiverrus haalistuu kauan ennen kiveä',
      problemP: 'Sää ja vuodet kuluttavat kultauksen, ja lopulta nimi tuskin näkyy. Kivenveistäjän tekemä uusinta maksaa satoja – siksi moni kivi seisoo tekstillä, jota ei enää voi lukea.',
      losningH: 'Täytä teksti itse, kirjain kirjaimelta',
      losningP: 'Kynä, jossa on öljypohjainen, säänkestävä väri ja ohut kärki, tehty kiveen kaiverretulle tekstille. Seuraa kirjainten uria rauhallisesti – väri kuivuu nopeasti ja kestää sateen ja pakkasen. Hiljaista työtä, joka näkyy seuraavalla käynnillä.',
      bullets: [
        '<strong>Nimi on taas luettavissa</strong> – peittävä väri, tehty kaiverretulle kivelle',
        '<strong>Kestää ulkona</strong> – öljypohjainen, säänkestävä väri kestää sateen ja pakkasen',
        '<strong>Tarkka työskennellä</strong> – ohut kärki seuraa kirjainten uria',
        '<strong>Kuiva ennen kuin lähdet</strong> – väri kuivuu nopeasti valumatta',
        '<strong>Sävy kiven mukaan</strong> – kulta, musta, valkoinen, hopea, punainen tai sininen, 20 ml',
      ],
      option: 'Väri', varden: ['Kulta', 'Musta', 'Valkoinen', 'Hopea', 'Punainen', 'Sininen'],
      alt: { main: 'Hautakivikynä täyttää kullattua tekstiä märällä kivellä', vattentat: 'Väri on vedenpitävä – kynää käytetään sateessa', matt: 'Mittakuva – kynä on 14,3 cm pitkä, kärki Ø 1,4 cm', forefter: 'Ennen ja jälkeen – haalistunut ja täytetty kaiverrus', guld: 'Kynä kullanvärisenä', silver: 'Kynä hopeana', svart: 'Kynä mustana', vit: 'Kynä valkoisena', rod: 'Kynä punaisena' },
    },
    en: {
      titel: 'Gravestone Pen – Restores Faded Inscriptions',
      problemH: 'The inscription fades long before the stone',
      problemP: "Weather and years wear away the gilding until the name can barely be read. Having a stonemason re-letter it costs hundreds – so many stones stand with text that's slipping away.",
      losningH: 'Restore the lettering yourself, letter by letter',
      losningP: "A pen with oil-based, weather-resistant paint and a fine tip, made for engraved lettering in stone. Follow the grooves at your own pace – the paint dries quickly and stands up to rain and frost. Quiet work that makes a real difference next time you visit.",
      bullets: [
        '<strong>The name can be read again</strong> – opaque paint made for engraved stone',
        '<strong>Stands up to the weather</strong> – oil-based paint that handles rain and frost',
        '<strong>Easy to work precisely</strong> – fine tip that follows the letter grooves',
        "<strong>Dry before you leave</strong> – quick-drying, no runs",
        '<strong>A shade to match the stone</strong> – gold, black, white, silver, red or blue, 20 ml per pen',
      ],
      option: 'Colour', varden: ['Gold', 'Black', 'White', 'Silver', 'Red', 'Blue'],
      alt: { main: 'The gravestone pen restoring gilded text on wet stone', vattentat: 'The paint is waterproof – the pen used in rain', matt: 'Dimensions – the pen is 14.3 cm long, tip Ø 1.4 cm', forefter: 'Before and after – faded and restored inscription', guld: 'The pen in gold', silver: 'The pen in silver', svart: 'The pen in black', vit: 'The pen in white', rod: 'The pen in red' },
    },
  },

  kamouflagetejp: {
    sv: {
      titel: 'Kamouflagetejp 3-pack – Självhäftande Väv 5 × 450 cm',
      problemH: 'Blank utrustning syns längre bort än du gör',
      problemP: 'Kikaren, ficklampan, stativet – allt med blank yta blinkar i solen. Och vanlig tejp som döljer den lämnar klet som aldrig går bort.',
      losningH: 'Väv som gömmer utrustningen utan klister på ytan',
      losningP: 'Linda väven runt kikaren, ficklampan eller stativet – den fäster i sig själv, inte i utrustningen, och lämnar inga rester när du tar bort den. Tre rullar på 5 × 450 centimeter räcker till flera föremål, och den elastiska väven följer runda former.',
      bullets: [
        '<strong>Inga blanka ytor kvar</strong> – matt väv i kamouflagemönster',
        '<strong>Inga klisterrester</strong> – väven fäster i sig själv, inte i utrustningen',
        '<strong>Följer runda former</strong> – elastisk väv för handtag, kikare och stativ',
        '<strong>Räcker till mycket</strong> – 3 rullar × 450 cm i varje förpackning',
        '<strong>Mönster efter marken</strong> – djungel, ACU, snö eller öken',
      ],
      option: 'Mönster', varden: ['Djungel', 'ACU', 'Snö', 'Öken'],
      alt: { main: 'Kamouflagetejp i flera mönster på gräs', matt: 'Måttbild – rullen är 5 cm bred och 450 cm lång', anv: 'Tejpen runt ficklampa, verktyg, termos och kamera', m1: 'Tre rullar i djungelmönster', m2: 'Tre rullar i ACU-mönster', m3: 'Tre rullar i snömönster', m4: 'Tre rullar i ökenmönster' },
    },
    no: {
      titel: 'Kamuflasjeteip 3-pakk – Selvklebende Vev 5 × 450 cm',
      problemH: 'Blankt utstyr synes lenger unna enn du gjør',
      problemP: 'Kikkerten, lommelykten, stativet – alt med blank overflate blinker i solen. Og vanlig teip som skjuler den, etterlater klister som aldri går bort.',
      losningH: 'Vev som skjuler utstyret uten lim på overflaten',
      losningP: 'Surr veven rundt kikkerten, lommelykten eller stativet – den fester i seg selv, ikke i utstyret, og etterlater ingen rester når du tar den av. Tre ruller på 5 × 450 centimeter rekker til flere gjenstander, og den elastiske veven følger runde former.',
      bullets: [
        '<strong>Ingen blanke flater igjen</strong> – matt vev i kamuflasjemønster',
        '<strong>Ingen limrester</strong> – veven fester i seg selv, ikke i utstyret',
        '<strong>Følger runde former</strong> – elastisk vev for håndtak, kikkert og stativ',
        '<strong>Rekker til mye</strong> – 3 ruller × 450 cm i hver pakke',
        '<strong>Mønster etter terrenget</strong> – jungel, ACU, snø eller ørken',
      ],
      option: 'Mønster', varden: ['Jungel', 'ACU', 'Snø', 'Ørken'],
      alt: { main: 'Kamuflasjeteip i flere mønstre på gress', matt: 'Målbilde – rullen er 5 cm bred og 450 cm lang', anv: 'Teipen rundt lommelykt, verktøy, termos og kamera', m1: 'Tre ruller i jungelmønster', m2: 'Tre ruller i ACU-mønster', m3: 'Tre ruller i snømønster', m4: 'Tre ruller i ørkenmønster' },
    },
    da: {
      titel: 'Kamuflagetape 3-pak – Selvklæbende Væv 5 × 450 cm',
      problemH: 'Blankt udstyr ses længere væk end du gør',
      problemP: 'Kikkerten, lommelygten, stativet – alt med blank overflade blinker i solen. Og almindelig tape, der skjuler den, efterlader klister, der aldrig går væk.',
      losningH: 'Væv der skjuler udstyret uden lim på overfladen',
      losningP: 'Vikl vævet om kikkerten, lommelygten eller stativet – det hæfter i sig selv, ikke i udstyret, og efterlader ingen rester, når du tager det af. Tre ruller på 5 × 450 centimeter rækker til flere genstande, og det elastiske væv følger runde former.',
      bullets: [
        '<strong>Ingen blanke flader tilbage</strong> – mat væv i kamuflagemønster',
        '<strong>Ingen klisterrester</strong> – vævet hæfter i sig selv, ikke i udstyret',
        '<strong>Følger runde former</strong> – elastisk væv til håndtag, kikkert og stativ',
        '<strong>Rækker til meget</strong> – 3 ruller × 450 cm i hver pakke',
        '<strong>Mønster efter terrænet</strong> – jungle, ACU, sne eller ørken',
      ],
      option: 'Mønster', varden: ['Jungle', 'ACU', 'Sne', 'Ørken'],
      alt: { main: 'Kamuflagetape i flere mønstre på græs', matt: 'Målbillede – rullen er 5 cm bred og 450 cm lang', anv: 'Tapen om lommelygte, værktøj, termokande og kamera', m1: 'Tre ruller i junglemønster', m2: 'Tre ruller i ACU-mønster', m3: 'Tre ruller i snemønster', m4: 'Tre ruller i ørkenmønster' },
    },
    fi: {
      titel: 'Maastoteippi 3-pakkaus – Itsekiinnittyvä Kangas 5 × 450 cm',
      problemH: 'Kiiltävä varuste näkyy kauemmas kuin sinä',
      problemP: 'Kiikari, taskulamppu, jalusta – kaikki kiiltävä välkkyy auringossa. Ja tavallinen teippi, joka sen peittää, jättää liimaa joka ei lähde koskaan.',
      losningH: 'Kangas, joka piilottaa varusteet ilman liimaa pinnassa',
      losningP: 'Kiedo kangas kiikarin, taskulampun tai jalustan ympärille – se tarttuu itseensä, ei varusteeseen, eikä jätä jälkiä kun otat sen pois. Kolme rullaa, 5 × 450 senttiä, riittää moneen esineeseen, ja joustava kangas myötäilee pyöreitä muotoja.',
      bullets: [
        '<strong>Ei kiiltäviä pintoja</strong> – matta kangas maastokuviolla',
        '<strong>Ei liimajäämiä</strong> – kangas tarttuu itseensä, ei varusteeseen',
        '<strong>Myötäilee pyöreitä muotoja</strong> – joustava kangas kahvoille, kiikareille ja jalustoille',
        '<strong>Riittää moneen</strong> – 3 rullaa × 450 cm joka pakkauksessa',
        '<strong>Kuvio maaston mukaan</strong> – viidakko, ACU, lumi tai aavikko',
      ],
      option: 'Kuvio', varden: ['Viidakko', 'ACU', 'Lumi', 'Aavikko'],
      alt: { main: 'Maastoteippiä eri kuvioissa nurmella', matt: 'Mittakuva – rulla on 5 cm leveä ja 450 cm pitkä', anv: 'Teippi taskulampun, työkalun, termoksen ja kameran ympärillä', m1: 'Kolme rullaa viidakkokuviolla', m2: 'Kolme rullaa ACU-kuviolla', m3: 'Kolme rullaa lumikuviolla', m4: 'Kolme rullaa aavikkokuviolla' },
    },
    en: {
      titel: 'Camo Wrap 3-Pack – Self-Cling Fabric 5 × 450 cm',
      problemH: 'Shiny gear shows up further away than you do',
      problemP: 'Binoculars, torch, tripod – anything with a shiny surface flashes in the sun. And ordinary tape that hides it leaves residue that never comes off.',
      losningH: 'Fabric that hides your gear with no glue on the surface',
      losningP: "Wrap it around binoculars, a torch or a tripod – it clings to itself, not to your gear, and leaves nothing behind when you unwrap it. Three rolls of 5 × 450 centimetres cover plenty of kit, and the stretchy fabric follows curved shapes.",
      bullets: [
        '<strong>No shiny surfaces left</strong> – matte fabric in camouflage pattern',
        '<strong>No sticky residue</strong> – the fabric clings to itself, not your gear',
        '<strong>Follows curved shapes</strong> – stretchy weave for grips, binoculars and tripods',
        '<strong>Covers plenty</strong> – 3 rolls × 450 cm in every pack',
        '<strong>A pattern for the ground</strong> – jungle, ACU, snow or desert',
      ],
      option: 'Pattern', varden: ['Jungle', 'ACU', 'Snow', 'Desert'],
      alt: { main: 'Camo wrap in several patterns on grass', matt: 'Dimensions – each roll is 5 cm wide and 450 cm long', anv: 'The wrap on a torch, tool, flask and camera', m1: 'Three rolls in jungle pattern', m2: 'Three rolls in ACU pattern', m3: 'Three rolls in snow pattern', m4: 'Three rolls in desert pattern' },
    },
  },

  badshorts: {
    sv: {
      titel: 'Badshorts med Skämttryck – Rumpan Bak',
      problemH: 'Stranden har sett samma shorts i tjugo år',
      problemP: "Marinblått, svart, ett diskret palmblad. Och killen som 'inte behöver något' i present har redan allt – utom något som får hela sällskapet att skratta.",
      losningH: 'Shortsen som ser ut att ha glidit ner där bak',
      losningP: 'Framifrån: färgglada badshorts med tryck och snörning. Bakifrån: linningen ser ut att ha åkt ner – rumpan är en del av trycket, och första reaktionen är alltid densamma. Trycket ligger platt i tyget, så de känns som vanliga badshorts att ha på sig.',
      bullets: [
        '<strong>Får hela stranden att vända sig om</strong> – baksidan ser ut som en nedåkt linning',
        '<strong>Presenten han faktiskt använder</strong> – riktiga badshorts med snörning i midjan',
        '<strong>Trycket är en del av tyget</strong> – platt tryck, ingen 3D-yta som skaver',
        '<strong>Fyra motiv att välja på</strong> – hajar, cocktail, krabbor eller hawaiiblommor',
      ],
      optionDesign: 'Motiv', optionStorlek: 'Storlek',
      designer: ['Hajar', 'Cocktail', 'Krabbor', 'Hawaii'],
      alt: { tryck: 'Trycket är platt i tyget – ingen 3D-yta' },
    },
    no: {
      titel: 'Badeshorts med Spøketrykk – Rumpa Bak',
      problemH: 'Stranden har sett de samme shortsene i tjue år',
      problemP: "Marineblått, svart, et diskret palmeblad. Og han som 'ikke trenger noe' i gave har allerede alt – unntatt noe som får hele følget til å le.",
      losningH: 'Shortsen som ser ut som den har sklidd ned bak',
      losningP: 'Forfra: fargerike badeshorts med trykk og snøring. Bakfra: linningen ser ut som den har glidd ned – rumpa er en del av trykket, og den første reaksjonen er alltid den samme. Trykket ligger flatt i stoffet, så de kjennes som vanlige badeshorts å ha på.',
      bullets: [
        '<strong>Får hele stranden til å snu seg</strong> – baksiden ser ut som en nedglidd linning',
        '<strong>Gaven han faktisk bruker</strong> – ekte badeshorts med snøring i livet',
        '<strong>Trykket er en del av stoffet</strong> – flatt trykk, ingen 3D-overflate som gnager',
        '<strong>Fire motiver å velge mellom</strong> – haier, cocktail, krabber eller hawaiiblomster',
      ],
      optionDesign: 'Motiv', optionStorlek: 'Størrelse',
      designer: ['Haier', 'Cocktail', 'Krabber', 'Hawaii'],
      alt: { tryck: 'Trykket ligger flatt i stoffet – ingen 3D-overflate' },
    },
    da: {
      titel: 'Badeshorts med Sjovt Tryk – Numsen Bagpå',
      problemH: 'Stranden har set de samme shorts i tyve år',
      problemP: "Marineblå, sort, et diskret palmeblad. Og ham der 'ikke mangler noget' i gave har allerede alt – undtagen noget, der får hele selskabet til at grine.",
      losningH: 'Shortsene der ser ud til at være gledet ned bagpå',
      losningP: 'Forfra: farverige badeshorts med tryk og snøre. Bagfra: linningen ser ud til at være røget ned – numsen er en del af trykket, og den første reaktion er altid den samme. Trykket ligger fladt i stoffet, så de føles som almindelige badeshorts at have på.',
      bullets: [
        '<strong>Får hele stranden til at vende sig om</strong> – bagsiden ligner en nedgledet linning',
        '<strong>Gaven han faktisk bruger</strong> – rigtige badeshorts med snøre i taljen',
        '<strong>Trykket er en del af stoffet</strong> – fladt tryk, ingen 3D-overflade der gnaver',
        '<strong>Fire motiver at vælge imellem</strong> – hajer, cocktail, krabber eller hawaiiblomster',
      ],
      optionDesign: 'Motiv', optionStorlek: 'Størrelse',
      designer: ['Hajer', 'Cocktail', 'Krabber', 'Hawaii'],
      alt: { tryck: 'Trykket ligger fladt i stoffet – ingen 3D-overflade' },
    },
    fi: {
      titel: 'Vitsi-uimashortsit – Pylly Takana',
      problemH: 'Ranta on nähnyt samat shortsit kaksikymmentä vuotta',
      problemP: "Laivastonsininen, musta, hillitty palmunlehti. Ja mies joka 'ei tarvitse mitään' lahjaksi omistaa jo kaiken – paitsi jotain, joka saa koko seurueen nauramaan.",
      losningH: 'Shortsit, jotka näyttävät valuneen alas takaa',
      losningP: 'Edestä: värikkäät uimashortsit painatuksella ja kiristysnyörillä. Takaa: vyötärö näyttää valuneen alas – pylly on osa painatusta, ja ensireaktio on aina sama. Kuvio on painettu kankaaseen sileänä, joten päällä ne tuntuvat tavallisilta uimashortseilta.',
      bullets: [
        '<strong>Koko ranta kääntyy katsomaan</strong> – takapuoli näyttää valuneelta vyötäröltä',
        '<strong>Lahja jota hän oikeasti käyttää</strong> – kunnon uimashortsit kiristysnyörillä',
        '<strong>Kuvio on osa kangasta</strong> – sileä painatus, ei hankaavaa 3D-pintaa',
        '<strong>Neljä kuosia</strong> – hait, cocktail, ravut tai havaijinkukat',
      ],
      optionDesign: 'Kuosi', optionStorlek: 'Koko',
      designer: ['Hait', 'Cocktail', 'Ravut', 'Havaiji'],
      alt: { tryck: 'Kuvio on painettu kankaaseen sileänä – ei 3D-pintaa' },
    },
    en: {
      titel: 'Funny Swim Shorts – Cheeky Behind',
      problemH: 'The beach has seen the same shorts for twenty years',
      problemP: "Navy, black, a discreet palm leaf. And the guy who 'doesn't need anything' already owns everything – except something that makes the whole group laugh.",
      losningH: 'The shorts that look like they slipped down at the back',
      losningP: "From the front: colourful swim shorts with a print and a drawstring. From the back: the waistband looks like it's slid down – the bum is part of the print, and the first reaction is always the same. The print sits flat in the fabric, so they feel like ordinary swim shorts to wear.",
      bullets: [
        '<strong>Turns every head on the beach</strong> – the back looks like a slipped waistband',
        '<strong>The gift he actually uses</strong> – real swim shorts with a drawstring waist',
        '<strong>The print is part of the fabric</strong> – flat print, no 3D surface to chafe',
        '<strong>Four designs to pick from</strong> – sharks, cocktails, crabs or Hawaiian flowers',
      ],
      optionDesign: 'Design', optionStorlek: 'Size',
      designer: ['Sharks', 'Cocktails', 'Crabs', 'Hawaii'],
      alt: { tryck: 'The print sits flat in the fabric – no 3D surface' },
    },
  },
};

export const PRISER4 = {
  tankoverdrag: { SE: '489.00', NO: '439.00', DK: '369.00', FI: '54.90', UK: '28.99' },
  jattefotboll: { SE: '379.00', NO: '299.00', DK: '279.00', FI: '40.90', UK: '19.99' },
  benskydd: { SE: '389.00', NO: '309.00', DK: '279.00', FI: '41.90', UK: '20.99' },
  gravstenspenna: { SE: '269.00', NO: '209.00', DK: '219.00', FI: '28.90', UK: '15.99' },
  kamouflagetejp: { SE: '289.00', NO: '229.00', DK: '239.00', FI: '33.90', UK: '14.99' },
  badshorts: { SE: '399.00', NO: '329.00', DK: '289.00', FI: '42.90', UK: '21.99' },
};
